project:
  type: book
  output-dir: docs
  resources: 
    - datasets/**
  
book:
  site-url: "https://greenquanteco.github.io/appl-biol-data-analysis/"
  repo-url: "https://github.com/greenquanteco/appl-biol-data-analysis"
  repo-actions: [edit, issue]
  cover-image: images/lab_logo_02.jpg
  title: "Applied Biological Data Analysis"
  date: "July 28, 2026"
  author:
  - name: Nick Green
    degrees:
    - Ph.D.
    orcid: 0000-0002-8538-4191
    email: ngreen62@kennesaw.edu
    affiliation:
      - name: Kennesaw State University
        department: "Department of Ecology, Evolution, and Organismal Biology"
        city: Kennesaw
        state: Georgia
        country: USA
        url: https://facultyweb.kennesaw.edu/ngreen62/index.php
  chapters:
    - index.qmd
    - part: chapters/part_01.qmd
      chapters:
        - chapters/ch01.qmd
    - part: chapters/part_02.qmd
      chapters:
        - chapters/ch02.qmd
        - chapters/ch03.qmd
        - chapters/ch04.qmd
        - chapters/ch05.qmd
    - part: chapters/part_03.qmd
      chapters:
        - chapters/ch06.qmd
        - chapters/ch07.qmd
        - chapters/ch08.qmd
        - chapters/ch09.qmd
        - chapters/ch10.qmd
        - chapters/ch11.qmd
    - part: chapters/part_04.qmd
      chapters:
        - chapters/ch12.qmd
        - chapters/ch13.qmd
        - chapters/ch14.qmd
        - chapters/ch15.qmd
    - part: chapters/part_05.qmd
      chapters:
        - chapters/ch16.qmd
        - chapters/ch17.qmd
        - chapters/ch18.qmd
        - chapters/ch19.qmd
    - part: chapters/part_06.qmd
      chapters:
        - chapters/ch20.qmd
        - chapters/ch21.qmd
    - part: chapters/part_07.qmd
      chapters:
        - chapters/ch22.qmd
        - chapters/ch23.qmd
        - chapters/ch24.qmd
        - chapters/ch25.qmd
    - part: chapters/part_08.qmd
      chapters:
        - chapters/ch26.qmd
        - chapters/ch27.qmd
    - part: chapters/part_09.qmd
      chapters:
        - chapters/ch28.qmd
  appendices:
    - chapters/ch29.qmd

license: "CC BY-SA"
copyright:
  holder: Nick Green
  year: 2026

bibliography: stat_refs.bib

csl: journal-of-mammalogy.csl

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    number-sections: true
    number-depth: 4
    fig-cap-location: top
    toc-depth: 3
    smooth-scroll: true
      
  pdf:
    mainfont: "Arial"
    monofont: "Courier New"
    documentclass: report
    toc: true
    number-sections: true
    number-depth: 4
    fig-cap-location: top
    keep-tex: true
    fontsize: "13"
    linestretch: 1.3
    geometry: 
     - margin=1in
    include-in-header: preamble.tex
    pdf-engine: xelatex
    fig-width: 6
    fig-height: 4
    

editor: source
crossref:
  fig-title: "Figure"
  tbl-title: "Table"
  
execute:
  freeze: auto
  echo: true
  warning: false
  message: false
  error: false
