<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>15&nbsp; Tests for differences in mean or location – Applied Biological Data Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/ch16.html" rel="next">
<link href="../chapters/ch14.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/part_04.html">Introductory statistics with R</a></li><li class="breadcrumb-item"><a href="../chapters/ch15.html"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Tests for differences in mean or location</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Applied Biological Data Analysis</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/greenquanteco/appl-biol-data-analysis" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../chapters/part_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistics in Modern Biology</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Statistics in biology</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../chapters/part_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">R data types and objects</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data import and export</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data manipulation with R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../chapters/part_03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploratory data analysis with R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Basic descriptive statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Summarizing biological data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Visualizing biological data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability distributions for biologists</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Comparing data to distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Data transformation and rescaling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Common problems in biological data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Planning your data analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../chapters/part_04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introductory statistics with R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Introductory statistics with R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch15.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Tests for differences in mean or location</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Tests for continous patterns</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Tests for contingency</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../chapters/part_05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Generalized linear models (GLM)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Introduction to generalized linear models (GLM)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">GLM for continuous response data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch20.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">GLM for count data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch21.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">GLM for categorical and proportional responses</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../chapters/part_06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extensions of GLMs: nonlinear and mixed models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch22.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Nonlinear methods for biology</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch23.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Random effects and mixed models</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../chapters/part_07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multivariate data analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch24.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Introduction to multivariate data and data analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch25.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Dissimilarity and distance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch26.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Clustering for biologists</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch27.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Ordination</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../chapters/part_08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Alternatives to *p*-values: information-theoretic and Bayesian methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch28.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Multivariate hypothesis testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch29.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Information theoretic model-based inference</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../chapters/part_09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bonus material</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch30.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Introduction to Bayesian inference for biologists</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch31.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Advanced R graphics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch32.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Classification and regression trees</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/appa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Appendix A</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-groups-1samp" id="toc-sec-groups-1samp" class="nav-link active" data-scroll-target="#sec-groups-1samp"><span class="header-section-number">15.1</span> Tests for 1 group</a>
  <ul class="collapse">
  <li><a href="#sec-groups-1samp-1t" id="toc-sec-groups-1samp-1t" class="nav-link" data-scroll-target="#sec-groups-1samp-1t"><span class="header-section-number">15.1.1</span> One-sample, one-tailed <em>t</em>-test</a></li>
  <li><a href="#sec-groups-1samp-2t" id="toc-sec-groups-1samp-2t" class="nav-link" data-scroll-target="#sec-groups-1samp-2t"><span class="header-section-number">15.1.2</span> One-sample, two-tailed <em>t</em>-test</a></li>
  </ul></li>
  <li><a href="#sec-groups-2samp" id="toc-sec-groups-2samp" class="nav-link" data-scroll-target="#sec-groups-2samp"><span class="header-section-number">15.2</span> Tests for 2 groups</a>
  <ul class="collapse">
  <li><a href="#sec-groups-2samp-2t" id="toc-sec-groups-2samp-2t" class="nav-link" data-scroll-target="#sec-groups-2samp-2t"><span class="header-section-number">15.2.1</span> Student’s <em>t</em>-test (Welch) (2-tail, 2-sample)</a></li>
  <li><a href="#sec-groups-2samp-1t" id="toc-sec-groups-2samp-1t" class="nav-link" data-scroll-target="#sec-groups-2samp-1t"><span class="header-section-number">15.2.2</span> Two-sample, one-tailed <em>t</em>-tests</a></li>
  <li><a href="#sec-groups-1samp-tost" id="toc-sec-groups-1samp-tost" class="nav-link" data-scroll-target="#sec-groups-1samp-tost"><span class="header-section-number">15.2.3</span> Equivalence testing</a></li>
  <li><a href="#sec-groups-2samp-wilcoxon" id="toc-sec-groups-2samp-wilcoxon" class="nav-link" data-scroll-target="#sec-groups-2samp-wilcoxon"><span class="header-section-number">15.2.4</span> Wilcoxon rank-sum test</a></li>
  </ul></li>
  <li><a href="#sec-groups-paired" id="toc-sec-groups-paired" class="nav-link" data-scroll-target="#sec-groups-paired"><span class="header-section-number">15.3</span> Tests for paired data</a>
  <ul class="collapse">
  <li><a href="#sec-groups-paired-pt" id="toc-sec-groups-paired-pt" class="nav-link" data-scroll-target="#sec-groups-paired-pt"><span class="header-section-number">15.3.1</span> Paired <em>t</em>-test</a></li>
  </ul></li>
  <li><a href="#sec-groups-ttests" id="toc-sec-groups-ttests" class="nav-link" data-scroll-target="#sec-groups-ttests"><span class="header-section-number">15.4</span> <em>t</em>-test summary</a></li>
  <li><a href="#sec-groups-more" id="toc-sec-groups-more" class="nav-link" data-scroll-target="#sec-groups-more"><span class="header-section-number">15.5</span> Tests for 3 or more groups</a>
  <ul class="collapse">
  <li><a href="#sec-groups-more-anova" id="toc-sec-groups-more-anova" class="nav-link" data-scroll-target="#sec-groups-more-anova"><span class="header-section-number">15.5.1</span> Analysis of variance</a></li>
  <li><a href="#sec-groups-more-kw" id="toc-sec-groups-more-kw" class="nav-link" data-scroll-target="#sec-groups-more-kw"><span class="header-section-number">15.5.2</span> Kruskal-Wallis test</a></li>
  </ul></li>
  <li><a href="#sec-groups-ord" id="toc-sec-groups-ord" class="nav-link" data-scroll-target="#sec-groups-ord"><span class="header-section-number">15.6</span> Tests with ordered factors</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/greenquanteco/appl-biol-data-analysis/edit/main/chapters/ch15.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/greenquanteco/appl-biol-data-analysis/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/part_04.html">Introductory statistics with R</a></li><li class="breadcrumb-item"><a href="../chapters/ch15.html"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Tests for differences in mean or location</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-groups" class="quarto-section-identifier"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Tests for differences in mean or location</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In a test for difference in mean or location, we are interested in whether observations differ between groups. Most of the time we are testing whether the central tendency differs between groups. A test of this kind evaluates a prediction like, “a typical value in group A is different from a typical value in group B”.</p>
<p>Alternatively, we can test for a difference in <strong>location</strong>: the relative position of random values from 2 or more groups. This is a slightly different statement: “values in group A tend to be greater than (or less than) values in group B”. Put another way: “If we pick a random value from group A, it will be reliably greater (or less than) than a random value from group B”. Tests for location are performed on the <strong>rank order</strong> of the values, not the values themselves.</p>
<p>When comparing groups, the data are usually best shown using a <strong>boxplot</strong>, also known as a <strong>box-and-whiskers</strong> plot. The exact implementation varies between software packages, but boxplots usually show the median, interquartile range (approximately), extreme values, and possible outliers (if any) Run the command <code>?boxplot.stats</code> to see a description of how boxplots are calculated in R.</p>
<section id="sec-groups-1samp" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="sec-groups-1samp"><span class="header-section-number">15.1</span> Tests for 1 group</h2>
<p>When all of the values come from the same set of observations, we can ask questions such as:</p>
<ul>
<li>Is the mean in this group equal to, or different from, some arbitrary value?</li>
<li>Is the mean in this group greater than, or not greater than, some arbitrary value?</li>
</ul>
<p>These questions are the domain of <strong>one-sample tests</strong>. The most important is the <strong>one-sample <em>t</em>-test</strong>, which comes in two varieties: <strong>one-tailed</strong> and <strong>two-tailed</strong>. All one-sample tests compare the mean of a set of values to some quantity (hypothetical mean) of interest, called <span class="math inline">\(\mu\)</span> (the Greek letter “mu”). In a one-tailed test, the null hypothesis is that the underlying population mean is either <span class="math inline">\(\le\mu\)</span> or <span class="math inline">\(\ge\mu\)</span>. In a two-tailed test, the null hypothesis is that the population mean is equal to <span class="math inline">\(\mu\)</span>.</p>
<div class="tip">
<p><strong>A note on symbology: sample vs.&nbsp;population parameters</strong></p>
<p>In statistics, we analyze <strong>samples</strong> (randomly-selected subsets of observed entities) to make inferences about <strong>populations</strong> (the hypothetical set of all possible entities which could be included in a sample). For example, if you wanted to know how the population of a nation of 100 million citizens felt about some political issue, it would be time-consuming and expensive to ask each citizen what they thought. Instead, you would sample a randomly selected set of 1000 citizens and then assume that those results reflected the opinion of the entire citizenry. For this assumption to work, your sample must be both random and representative of the entire population.</p>
<p>Similarly, in science we cannot collect a infinite amount of data, or measure every squirrel in the forest, or any other type of exhaustive and comprehensive data collection. We instead take representative samples of all the possible samples–i.e., the population–and rely on good practices in experimental design to enable us to assume that our sample represents the population.</p>
<p>The reason I bring this up here is that we need to keep in mind the difference between sample statistics and population statistics. <strong>Sample statistics</strong> are calculated from your data. <strong>Population statistics</strong> are <strong>inferred</strong> from your data using statistical models. This is why statistical tests are commonly referred to as <strong>inferential statistics</strong>, and why simple calculations from data are referred to as <strong>descriptive statistics</strong>.</p>
<p>The most common descriptive statistics are shown below:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th style="text-align: center;">Sample</th>
<th style="text-align: center;">Population</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean</td>
<td style="text-align: center;"><span class="math inline">\(\bar{x}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\mu\)</span></td>
</tr>
<tr class="even">
<td>Variance</td>
<td style="text-align: center;"><span class="math inline">\(s^{2}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\sigma^{2}\)</span></td>
</tr>
<tr class="odd">
<td>Standard deviation</td>
<td style="text-align: center;"><span class="math inline">\(s\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\sigma\)</span></td>
</tr>
</tbody>
</table>
</div>
<section id="sec-groups-1samp-1t" class="level3" data-number="15.1.1">
<h3 data-number="15.1.1" class="anchored" data-anchor-id="sec-groups-1samp-1t"><span class="header-section-number">15.1.1</span> One-sample, one-tailed <em>t</em>-test</h3>
<p>In a one-tailed one-sample test, we are interested in whether the underlying population mean (<span class="math inline">\(\mu\)</span>) of a set of values is not equal to some value of interest…either at most some value, or at least some value.</p>
<p><strong>Question:</strong> Is the mean value less than OR greater than some value <span class="math inline">\(x\)</span>?</p>
<p><strong>Null hypothesis:</strong> True mean is <span class="math inline">\(=x\)</span>.</p>
<p><strong>Alternative hypothesis:</strong> True mean is <span class="math inline">\(&lt;x\)</span> or true mean is <span class="math inline">\(&gt;x\)</span>.</p>
<p><strong>Example use case:</strong>Fred needs to check whether the mean measurement error across his 12 technicians is less than 0.5 mm.</p>
<p>Here is an example where we simulate some data in R and run a one-tailed one-sample <em>t</em>-test.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># simulate some values with nominal mean 5 and sd 3</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="dv">5</span>, <span class="dv">3</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 1 sample 1 tailed t-test</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Example 1: Is the underlying mean &lt;= 0?</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(a, <span class="at">alternative=</span><span class="st">"greater"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  a
t = 8.3142, df = 19, p-value = 4.707e-08
alternative hypothesis: true mean is greater than 0
95 percent confidence interval:
 4.29664     Inf
sample estimates:
mean of x 
 5.424871 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example 2: Is the underlying mean &lt;= 4?</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(a, <span class="at">alternative=</span><span class="st">"greater"</span>, <span class="at">mu=</span><span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  a
t = 2.1838, df = 19, p-value = 0.02086
alternative hypothesis: true mean is greater than 4
95 percent confidence interval:
 4.29664     Inf
sample estimates:
mean of x 
 5.424871 </code></pre>
</div>
</div>
<p>Interpretation: In the example above, the researcher can reject the null hypothesis that the true mean is <span class="math inline">\(\leq4\)</span>, and conclude that the true mean is <span class="math inline">\(&gt;4\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example 3: Is the underlying mean &gt;= 5.5?</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(a, <span class="at">alternative=</span><span class="st">"less"</span>, <span class="at">mu=</span><span class="fl">5.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  a
t = -0.11514, df = 19, p-value = 0.4548
alternative hypothesis: true mean is less than 5.5
95 percent confidence interval:
     -Inf 6.553102
sample estimates:
mean of x 
 5.424871 </code></pre>
</div>
</div>
<p>Interpretation: In example 3, the researcher cannot reject the null hypothesis that <span class="math inline">\(\mu\geq5.5\)</span>. This makes sense, because the true mean is about <span class="math inline">\(5.4\pm2.9\)</span> (verify with <code>mean(a);sd(a)</code>).</p>
</section>
<section id="sec-groups-1samp-2t" class="level3" data-number="15.1.2">
<h3 data-number="15.1.2" class="anchored" data-anchor-id="sec-groups-1samp-2t"><span class="header-section-number">15.1.2</span> One-sample, two-tailed <em>t</em>-test</h3>
<p>In a two-tailed test, we are interested in whether the underlying population mean of a set of values is <strong>equal</strong> to some value of interest.</p>
<p><strong>Question:</strong> Is the underlying true mean equal to, or different from, some value <span class="math inline">\(\mu\)</span>?</p>
<p><strong>Null hypothesis:</strong> True mean <span class="math inline">\(=\mu\)</span>.</p>
<p><strong>Alternative hypothesis:</strong> True mean <span class="math inline">\(\neq\mu\)</span></p>
<p><strong>Example use case:</strong> Wilma needs to test whether the mean pH of her prepared stock solution is equal to, or different from, the target pH of 7.7.</p>
<p>Here is an example where we simulate some data and conduct a one-sample, two-tailed <em>t</em>-test.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># simulate data</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 1 sample 2-tailed t-test:</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Example 1: mu = 0 (default)</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(a)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  a
t = 14.445, df = 19, p-value = 1.067e-11
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 2.686402 3.596845
sample estimates:
mean of x 
 3.141624 </code></pre>
</div>
</div>
<p>Interpretation: In the example above, the researcher can reject the null that the true mean = 0, and conclude that the true mean is significantly different from 0.</p>
<p>Here’s another example with a different dataset and test.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># simulate data</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 1 sample 2-tailed t-test:</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Example 2: mu = 5</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(a, <span class="at">mu=</span><span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  a
t = -8.5445, df = 19, p-value = 6.218e-08
alternative hypothesis: true mean is not equal to 5
95 percent confidence interval:
 2.686402 3.596845
sample estimates:
mean of x 
 3.141624 </code></pre>
</div>
</div>
<p>Interpretation: The researcher can reject the null hypothesis that the mean = 5, and conclude that the true mean is not 5. Note that this includes both <span class="math inline">\(&lt;5\)</span> and <span class="math inline">\(&gt;5\)</span> as possibilities, but the direction is obvious from the sample mean.</p>
</section>
</section>
<section id="sec-groups-2samp" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="sec-groups-2samp"><span class="header-section-number">15.2</span> Tests for 2 groups</h2>
<section id="sec-groups-2samp-2t" class="level3" data-number="15.2.1">
<h3 data-number="15.2.1" class="anchored" data-anchor-id="sec-groups-2samp-2t"><span class="header-section-number">15.2.1</span> Student’s <em>t</em>-test (Welch) (2-tail, 2-sample)</h3>
<p>When most people say “<em>t</em>-test”, what they usually mean is a two-sample, two-tailed <em>t</em>-test that tests for a <strong>difference in means between two groups</strong>. The original version was introduced as the <strong>Student’s <em>t</em>-test</strong> by William Sealy Gosset in 1908<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>; modern software uses a modified version called the <strong>Welch <em>t</em>-test</strong> (or sometimes the “<strong>Welch-Satterthwaite <em>t</em>-test</strong>”, but this is not quite correct). The newer version is better at accounting for non-normality and unequal variances.</p>
<p>The test statistic, <em>t</em>, is basically the difference in sample means scaled by the variance in each group and the sample size in each group. It is calculated as:</p>
<p><span class="math display">\[
t = \frac{\bar{x}_1-\bar{x}_2}
{\sqrt{\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}}}
\]</span></p>
<p>where <span class="math inline">\(\bar{x_1}\)</span> and <span class="math inline">\(\bar{x_2}\)</span> are the sample means, <span class="math inline">\(s_1^2\)</span> and <span class="math inline">\(s_2^2\)</span> are the sample variances, and <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> are the sample sizes. Think through that equation…what would increasing the difference in means (the numerator) do to <em>t</em>? What about increasing one or both sample sizes? One or both sample variances?</p>
<p>Basically, the numerator of <em>t</em> is the quantity of interest: the difference in means between two groups. The denominator is the standard error (SE) of that estimate.</p>
<p>A <em>t</em> value by itself doesn’t tell you much, though, because what we’re interested in is how likely that <em>t</em> score is relative to the number of degrees of freedom (DF) in the dataset. While the early users would simply use <em>n-1</em> as the DF, modern <em>t</em>-statistics and <em>t</em> distributions are defined by a newer version of the degrees of freedom calculation:</p>
<p><span class="math display">\[
df =
\frac{
\left(
\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}
\right)^2
}{
\frac{\left(s_1^2/n_1\right)^2}{n_1-1}
+
\frac{\left(s_2^2/n_2\right)^2}{n_2-1}
}
\]</span></p>
<p>Say you perform a test comparing groups A and B, and the <em>t</em> statistic comes out to be 1.95. We have to compare that to the <em>t</em> distribution with the number of DF contained in the data, which might be 31.2:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch15_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The question for the hypothesis test is: in a dataset with 31.2 DF, how often should we observe <em>t</em> values at least as large as 1.95 (i.e., <span class="math inline">\(\left|t\right|\ge1.95\)</span>)? That proportion is the area shaded below:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch15_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The area of the left shaded area is <code>pt(-1.95, 31.2)</code>, which is <code>0.0301</code>. The distribution is symmetrical, so <span class="math inline">\(p\left(\left|t\right|\ge1.95\right)=0.0301\times2=0.0602\)</span>. Thus, the test was not significant (<em>t</em> = 1.95, 31.2 d.f., <em>p</em> = 0.06).</p>
<p><strong>Question:</strong> Do two groups have the same underlying population mean?</p>
<p><strong>Null hypothesis:</strong> The true difference in means = 0. I.e., <span class="math inline">\(\mu_1=\mu_2\)</span>.</p>
<p><strong>Alternative hypothesis:</strong> True difference in means is <span class="math inline">\(\neq0\)</span>. I.e., <span class="math inline">\(\mu_1\neq\mu_2\)</span>.</p>
<p><strong>Example use case:</strong> Barney needs to test whether tomato plants treated with a new pesticide have a different yield (g tomato / plant) than plants in the untreated control group.</p>
<p>Below is an example where we simulate some data and run a two-sample, two-tailed test to compare the means of two groups.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># simulate data</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">5</span>, <span class="dv">2</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">3</span>, <span class="dv">2</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># example 1: difference in means</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(a,b)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  a and b
t = 8.1211, df = 194.18, p-value = 5.241e-14
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 1.696004 2.783990
sample estimates:
mean of x mean of y 
 5.065030  2.825033 </code></pre>
</div>
</div>
<p>Interpretation: The researcher should conclude that there is a statistically significant difference between the means of groups a and b. In a manuscript, you should report the test statistic, the DF, and the <em>p</em>-value. E.g., “There was a significant difference in means between group a and group b (<span class="math inline">\(t=8.121\)</span>, 194.18 d.f., <span class="math inline">\(p&lt;0.001\)</span>).” Notice that values are rounded to 2 or 3 decimal places, which is usually enough for biology. This is especially true for the <em>p</em>-value, which can be approximated by R down to infinitesimally small values. I always round those to 0.001 or 0.0001.</p>
<p>A <em>t</em>-test can also be performed using the <strong>formula</strong> interface, which is an R programming construct for specifying a response variable and its predictors. Notice that the formula interface here is the same as used in <code>boxplot()</code> (<a href="ch08.html#sec-plot1-sing-box" class="quarto-xref"><span>Section 8.1.3</span></a>) and <code>aggregate()</code> (<a href="ch07.html#sec-summ-agg" class="quarto-xref"><span>Section 7.1.1</span></a>).</p>
<p><strong>Syntax note:</strong> Formula syntax has the response variable on the left, then a <code>~</code>, then the predictor or predictors. For predictors, <code>a + b</code> means an additive model; while <code>a * b</code> specifies an interaction. For a <em>t</em>-test, there can be only 1 predictor. If you want to test <span class="math inline">\(&gt;1\)</span> predictor at a time, you need to use ANOVA instead.</p>
<p>Here are some common formula examples:</p>
<div id="tbl-model-formulas" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-formulas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.1: Common R model formulas and their meanings.
</figcaption>
<div aria-describedby="tbl-model-formulas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Formula</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>y ~ x</code></td>
<td><code>y</code> is modeled as a function of <code>x</code>.</td>
</tr>
<tr class="even">
<td><code>y ~ x1 + x2</code></td>
<td><code>y</code> is modeled as a function of <code>x1</code> and <code>x2</code>, with their effects treated as <strong>additive</strong> (i.e., no interaction between them is included).</td>
</tr>
<tr class="odd">
<td><code>y ~ x1 * x2</code></td>
<td><code>y</code> is modeled as a function of <code>x1</code>, <code>x2</code>, and their <strong>interaction</strong>. An interaction means that the effect of one predictor depends on the value of the other predictor. This is shorthand for <code>y~x1 + x2 + x1:x2</code>.</td>
</tr>
<tr class="even">
<td><code>y ~ 1</code></td>
<td><code>y</code> is modeled using only a constant (the intercept), with no predictors. This is often called an <strong>intercept-only</strong> or <strong>null model</strong>.</td>
</tr>
<tr class="odd">
<td><code>y ~ 0 + x</code></td>
<td><code>y</code> is modeled as a function of <code>x</code>, but without an intercept (i.e., the intercept is constrained to 0).</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The formula interface is used in several contexts in R, including plotting, modeling, and aggregating.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pull some data from example dataset iris</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># i.e., make a new data frame with only 2 groups</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>dx <span class="ot">&lt;-</span> iris[<span class="fu">which</span>(iris<span class="sc">$</span>Species <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"setosa"</span>, <span class="st">"versicolor"</span>)),]</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># perform the test.</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Petal.Length<span class="sc">~</span>Species, <span class="at">data=</span>dx)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Petal.Length by Species
t = -39.493, df = 62.14, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group setosa and group versicolor is not equal to 0
95 percent confidence interval:
 -2.939618 -2.656382
sample estimates:
    mean in group setosa mean in group versicolor 
                   1.462                    4.260 </code></pre>
</div>
</div>
<p>Interpretation: The researcher should conclude that there is a statistically significant difference between the mean petal length of <em>Iris setosa</em> and <em>Iris versicolor</em>.</p>
</section>
<section id="sec-groups-2samp-1t" class="level3" data-number="15.2.2">
<h3 data-number="15.2.2" class="anchored" data-anchor-id="sec-groups-2samp-1t"><span class="header-section-number">15.2.2</span> Two-sample, one-tailed <em>t</em>-tests</h3>
<p><strong>Question:</strong> Is the true difference in means between 2 groups greater than, or less than, some target value <span class="math inline">\(\mu\)</span>?</p>
<p><strong>Null hypothesis:</strong> The true difference in means between 2 groups is <span class="math inline">\(\mu\)</span>. I.e., <span class="math inline">\(\mu_1-\mu_2=\mu\)</span>.</p>
<p><strong>Alternative hypothesis:</strong> The true difference in means between 2 groups is either greater than <span class="math inline">\(&gt;\mu\)</span> or <span class="math inline">\(&lt;\mu\)</span>. I.e., either <span class="math inline">\(\mu_1-\mu_2&gt;\mu\)</span> or <span class="math inline">\(\mu_1-\mu_2&lt;\mu\)</span>.</p>
<p><strong>Example use case:</strong> Betty needs to compare two stock solutions and check that their pH differs by no more than 0.2.</p>
<p>The 2-sample, 1-tailed <em>t</em>-test that can be used in several ways:</p>
<ol type="1">
<li>Test whether the mean in one group is greater or less than the mean in another group.</li>
<li>Test whether the the mean in one group is greater or less than the mean in another group, and that the difference is at least some specified value.</li>
</ol>
<p>For example, if you know that the mean of group 1 must be less than the mean in group 2, and will not even consider that the mean of group 2 is less than that of group 1, then you could run a 2-sample 1-tailed test.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># simulate data</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">789</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="dv">10</span>, <span class="dv">1</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="dv">12</span>, <span class="dv">1</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># is mean(x1) &gt; mean(x2)?</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x1, x2, <span class="at">alternative=</span><span class="st">"greater"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  x1 and x2
t = -8.8728, df = 37.99, p-value = 1
alternative hypothesis: true difference in means is greater than 0
95 percent confidence interval:
 -2.402592       Inf
sample estimates:
mean of x mean of y 
 9.689982 11.708940 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># is mean(x1) &lt; mean(x2)?</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x1, x2, <span class="at">alternative=</span><span class="st">"less"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  x1 and x2
t = -8.8728, df = 37.99, p-value = 4.259e-11
alternative hypothesis: true difference in means is less than 0
95 percent confidence interval:
      -Inf -1.635323
sample estimates:
mean of x mean of y 
 9.689982 11.708940 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># is mean(x1) - mean(x2) at least 1?</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x1, x2, <span class="at">alternative=</span><span class="st">"greater"</span>, <span class="at">mu=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  x1 and x2
t = -13.267, df = 37.99, p-value = 1
alternative hypothesis: true difference in means is greater than 1
95 percent confidence interval:
 -2.402592       Inf
sample estimates:
mean of x mean of y 
 9.689982 11.708940 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># is mean(x1) - mean(x2) at most 1?</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x1, x2, <span class="at">alternative=</span><span class="st">"less"</span>, <span class="at">mu=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  x1 and x2
t = -13.267, df = 37.99, p-value = 3.867e-16
alternative hypothesis: true difference in means is less than 1
95 percent confidence interval:
      -Inf -1.635323
sample estimates:
mean of x mean of y 
 9.689982 11.708940 </code></pre>
</div>
</div>
<p>an uncommon variant used to test whether two groups have a difference in means that is less than or greater than some specified value. For example, if you produce two batches of bacteria by inoculation, incubation, and then serial dilution, you may want to confirm that the difference in cell count between them is less than some acceptable value. You could use a 2-sample, 1-tailed test with the “alternative” hypothesis being that the difference is “greater” than your benchmark.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">789</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">5</span>, <span class="dv">2</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="fl">5.5</span>, <span class="dv">2</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># is the true difference in means &lt;1?</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x1, x2, <span class="at">alternative=</span><span class="st">"greater"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  x1 and x2
t = -2.6676, df = 50.08, p-value = 0.9949
alternative hypothesis: true difference in means is greater than 0
95 percent confidence interval:
 -2.048126       Inf
sample estimates:
mean of x mean of y 
 4.438104  5.696001 </code></pre>
</div>
</div>
</section>
<section id="sec-groups-1samp-tost" class="level3" data-number="15.2.3">
<h3 data-number="15.2.3" class="anchored" data-anchor-id="sec-groups-1samp-tost"><span class="header-section-number">15.2.3</span> Equivalence testing</h3>
<p>It is not possible to demonstrate statistically that a difference in means is truly 0, or that the underlying mean of a set of data truly is equal to a target value <span class="math inline">\(\mu\)</span> (the converse of a one-sample, two-tailed <em>t</em>-test). With a 1-sample, 2-tailed test the best you can do is “fail to reject” the null hypothesis that the mean is 0. However, we can show that the difference is arbitrarily close to 0. This approach is called <strong>equivalence testing</strong>, and one method is the <strong>two one-sided tests</strong> (<strong>TOST</strong>) method. The method works like this:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>Illustration of the two one-sided test (TOST) strategy for establishing that a sample, or set of differences, has an underlying mean arbitrarily close to some value <span class="math inline">\(\mu\)</span> (<span class="math inline">\(\mu=0\)</span> in this example.)</figcaption>
<p><img src="../images/review-03.jpg" class="img-fluid figure-img"></p>
</figure>
</div>
<p>Here is a worked TOST equivalence test example in R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># simulate data</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">5</span>, <span class="dv">1</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">5</span>, <span class="dv">1</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># let target tolerance = 1</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co"># note that total tolerance range is 1, so</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="co"># amount for both one-sided tests is 1/2==0.5</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co"># test 1: is difference &gt;-D?</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(a, b, <span class="at">alternative =</span> <span class="st">"greater"</span>, <span class="at">mu=</span><span class="sc">-</span>D)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  a and b
t = 4.4956, df = 194.18, p-value = 5.955e-06
alternative hypothesis: true difference in means is greater than -0.5
95 percent confidence interval:
 -0.1079329        Inf
sample estimates:
mean of x mean of y 
 5.032515  4.912516 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># test 2: is difference &lt;D?</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(a, b, <span class="at">alternative =</span> <span class="st">"less"</span>, <span class="at">mu=</span>D)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  a and b
t = -2.7554, df = 194.18, p-value = 0.00321
alternative hypothesis: true difference in means is less than 0.5
95 percent confidence interval:
    -Inf 0.34793
sample estimates:
mean of x mean of y 
 5.032515  4.912516 </code></pre>
</div>
</div>
<p>Interpretation: Test 1 showed that the difference in means is <span class="math inline">\(&gt;-0.5\)</span>. Test 2 showed that the difference in means is <span class="math inline">\(&lt;0.5\)</span>. So, the difference in means is in the interval <span class="math inline">\(\left(-0.5,0.5\right)\)</span>, which means the difference in means is at most 0.5 in either direction.</p>
</section>
<section id="sec-groups-2samp-wilcoxon" class="level3" data-number="15.2.4">
<h3 data-number="15.2.4" class="anchored" data-anchor-id="sec-groups-2samp-wilcoxon"><span class="header-section-number">15.2.4</span> Wilcoxon rank-sum test</h3>
<p><strong>Question:</strong> Are values in one group consistently greater than or less than those in another group? OR: Is the median rank in one group different from that in another group?</p>
<p><strong>Null hypothesis:</strong> For randomly selected values <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> from two groups, <span class="math inline">\(p\left(x&gt;y\right)=p\left(y&gt;x\right)\)</span>.</p>
<p><strong>Alternative hypothesis:</strong> For randomly selected values X and Y from two groups, <span class="math inline">\(p\left(x&gt;y\right)\neq p\left(y&gt;x\right)\)</span>.</p>
<p><strong>Example use case:</strong> Homer is interested in whether plots where invasive plants have been removed have more squirrels than plots where invasive plants are not removed, but does not want to model the actual number of squirrels.</p>
<p>The <strong>Mann-Whitney <em>U</em> test</strong>, also known as the <strong>Wilcoxon test</strong>, is a nonparametric alternative to the two-sample <em>t</em>-test. <strong>Nonparametric</strong> means that the test does not make restrictive assumptions about the distribution of the data or a test statistic. Nonparametric tests are often based on the <strong>ranks</strong> of the data: the smallest value is rank 1, the next smallest is rank 2, and so on. Because of this, nonparametric tests allow you make statements about how consistent a pattern is, rather than about the actual values.</p>
<p>This test has two common use cases:</p>
<ul>
<li><p>The researcher is only interested in whether values in one group are consistently larger than those in another group.</p></li>
<li><p>The researcher needs to perform a <em>t</em>-test, but the data do not meet the assumptions of the <em>t</em>-test.</p></li>
</ul>
<p>The syntax for the Wilcoxon test is fairly similar to that of a <em>t</em>-test.</p>
<p>Example Wilcoxon test in R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># simulate some data:</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">20</span>, <span class="dv">1</span>, <span class="dv">6</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">20</span>, <span class="dv">4</span>, <span class="dv">9</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co"># run the test</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(a,b)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum exact test

data:  a and b
W = 35, p-value = 1.126e-06
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>Here is the same kind of test, but using the formula interface. You can use the formula interface for <em>t</em>-tests as well.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pull some data from example dataset iris</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># i.e., make a new data frame with only 2 groups</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>use.species <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"versicolor"</span>, <span class="st">"virginica"</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>dx <span class="ot">&lt;-</span> iris[<span class="fu">which</span>(iris<span class="sc">$</span>Species <span class="sc">%in%</span> use.species),]</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>dx<span class="sc">$</span>Species <span class="ot">&lt;-</span> <span class="fu">factor</span>(dx<span class="sc">$</span>Species, <span class="at">levels=</span>use.species)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co"># perform the test.</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(Petal.Length<span class="sc">~</span>Species, <span class="at">data=</span>dx)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  Petal.Length by Species
W = 44.5, p-value &lt; 2.2e-16
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>Interpretation: The researcher can say that values in one group are consistently greater than values in the other group. Which way that goes should be obvious from looking at the sample medians or a boxplot.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># follow up the test with a boxplot</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># note that the formula interface is used here as well!</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Petal.Length<span class="sc">~</span>Species, <span class="at">data=</span>dx)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch15_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>When sample sizes or effect sizes are large, the Wilcoxon test and the <em>t</em>-test will often give the same answers in terms of significance vs. nonsignificance.</p>
<p>Because the <em>t</em>-test tests for a difference in means, and the Wilcoxon is its rank-based alternative, some people think that the Wilcoxon test is a test for a difference in medians…but this is <strong>not correct</strong>. It’s more accurate to say that the Wilcoxon test tests for a median difference.</p>
</section>
</section>
<section id="sec-groups-paired" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="sec-groups-paired"><span class="header-section-number">15.3</span> Tests for paired data</h2>
<section id="sec-groups-paired-pt" class="level3" data-number="15.3.1">
<h3 data-number="15.3.1" class="anchored" data-anchor-id="sec-groups-paired-pt"><span class="header-section-number">15.3.1</span> Paired <em>t</em>-test</h3>
<p><strong>Question:</strong> Is the mean of the differences of paired observations = 0, or different from 0?</p>
<p><strong>Null hypothesis:</strong> Mean of pairwise differences = 0.</p>
<p><strong>Alternative hypothesis:</strong> Mean of pairwise differences <span class="math inline">\(\neq0\)</span>.</p>
<p><strong>Example use case:</strong> Pebbles needs to test for a mean change in the body mass of individual mice before and after a feeding trial. Each mouse is weighed both before and after the trial.</p>
<p>Many biological experiments involved <strong>paired samples</strong>, where a single unit or entity was measured twice. For example, a single mouse might be weighed before and after a feeding trial. In a <strong>paired <em>t</em>-test</strong>, we test whether or not the mean of differences is 0. This is subtly different than the test for differences in means evaluated in a two-sample test. Consequently, a paired <em>t</em>-test is tantamount to a one-sample test on the pairwise differences. Compare the null hypotheses tested by the two-sample <em>t</em>-test and paired <em>t</em>-test below:</p>
<p><strong>Two-sample <em>t</em>-test:</strong> <span class="math inline">\(\frac{\sum_{i=1}^{n_1}x_{1,i}}{n_1}=\frac{\sum_{i=1}^{n_2}x_{2,i}}{n_2}\)</span></p>
<p><strong>Paired <em>t</em>-test:</strong> <span class="math inline">\(\frac{\sum_{i=1}^{n}{x_{1,i}-x_{2,i}}}{n}=0\)</span></p>
<p>Let’s simulate some data, conduct a paired <em>t</em>-test, and convince ourselves that the paired <em>t</em>-test is equivalent to a one-sample test on pairwise differences.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example paired t-test in R</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># simulate data</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">5</span>, <span class="dv">2</span>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co"># add pair-wise differences</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> a <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">2</span>, <span class="fl">0.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Interpretation: The researcher should conclude that the mean difference for each subject was significantly different from 0, at -1.98 with a 95% CI of [-2.02, -1.95].</p>
<p>Note that the paired <em>t</em>-test gives essentially the same result as conducting a one-sample test on the pair-wise differences.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare to one sample t-test on differences:</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>dif <span class="ot">&lt;-</span> b <span class="sc">-</span> a</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(dif)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  dif
t = 109.63, df = 99, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 1.946622 2.018385
sample estimates:
mean of x 
 1.982503 </code></pre>
</div>
</div>
</section>
</section>
<section id="sec-groups-ttests" class="level2" data-number="15.4">
<h2 data-number="15.4" class="anchored" data-anchor-id="sec-groups-ttests"><span class="header-section-number">15.4</span> <em>t</em>-test summary</h2>
<p>As we have seen, the <em>t</em>-test in all of its variations is a very useful and flexible family of tests that can be applied to many biological problems. One of the reasons that <em>t</em>-tests are so widely applicable-and why there are so many <em>t</em>-tests–is that the test statistic <em>t</em> is so elegant in its construction: it represents the quantity of interest directly in its numerator, and then the denominator scales that quantity according to the level of uncertainty in the data. It is thus a kind of <strong>signal-to-noise ratio</strong> that predated information theory by almost 50 years.</p>
<p>As a review, the table below summarizes the different <em>t</em>-tests and their use cases:</p>
<div id="tbl-t-tests" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-t-tests-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.2: Common types of <em>t</em>-tests and the hypotheses they evaluate.
</figcaption>
<div aria-describedby="tbl-t-tests-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Type</th>
<th>Use</th>
<th>Section</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One-sample <em>t</em>-test, one-tailed</td>
<td>Tests whether the population mean of a single set of values is less than or greater than a specified value <span class="math inline">\(\mu_0\)</span>. Appropriate when differences in only one direction are of interest.</td>
<td><a href="#sec-groups-1samp-1t" class="quarto-xref"><span>Section 15.1.1</span></a></td>
</tr>
<tr class="even">
<td>One-sample <em>t</em>-test, two-tailed</td>
<td>Tests whether the population mean is equal to a specified value <span class="math inline">\(\mu_0\)</span> (null hypothesis) or differs from it (alternative hypothesis).</td>
<td><a href="#sec-groups-1samp-2t" class="quarto-xref"><span>Section 15.1.2</span></a></td>
</tr>
<tr class="odd">
<td>Two-sample <em>t</em>-test, two-tailed</td>
<td>Tests whether the population means of two groups (<span class="math inline">\(\mu_1\)</span> and <span class="math inline">\(\mu_2\)</span>) differ. This can also be thought of as testing whether the difference between the means is equal to 0. Welch’s <em>t</em>-test, which does not assume equal variances, should generally be used and is the default in R.</td>
<td><a href="#sec-groups-2samp-2t" class="quarto-xref"><span>Section 15.2.1</span></a></td>
</tr>
<tr class="even">
<td>Two-sample <em>t</em>-test, one-tailed</td>
<td>Tests whether the population mean of one group (<span class="math inline">\(\mu_1\)</span>) is less than or greater than the mean of another group (<span class="math inline">\(\mu_2\)</span>). Appropriate when differences in only one direction are of interest.</td>
<td><a href="#sec-groups-2samp-1t" class="quarto-xref"><span>Section 15.2.2</span></a></td>
</tr>
<tr class="odd">
<td>Paired <em>t</em>-test</td>
<td>Tests whether the mean difference between paired observations differs from a specified value <span class="math inline">\(D_0\)</span>, usually 0. The test may be one- or two-tailed depending on the hypothesis.</td>
<td><a href="#sec-groups-paired-pt" class="quarto-xref"><span>Section 15.3.1</span></a></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The number of “samples” in a <em>t</em>-test refers to how many sets of observations are being compared. There can be either 1 sample (all observations compared to some value) or 2 samples (2 sets of observations compared to each other).</p>
<p>The number of “tails” refers to how sides (left (negative) and/or right (positive)) are of interest in the test statistic distribution. In a two-tailed test, or two-sided test, an extreme test statistic could fall in either the right or the left tail of the distribution. The figure below shows the range of <em>t</em> values which would be declared significant for each kind of test. Notice that for a one-tailed test, the significance region extends closer to the center, because its area must be equal to the same <span class="math inline">\(\alpha\)</span> as a two-tailed test.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch15_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The <em>t</em>-test is usually one of the first methods taught because its use cases are simple, and its test statistic is pretty easy to understand. Consider the original <em>t</em> statistic introduced to the English statistics literature by Gosset and popularized as “Student’s <em>t</em>” by Fisher:</p>
<p><span class="math display">\[
t=\frac{\bar{x_1}-\bar{x_2}}{\sqrt{\frac{s_{x_1}^2+s_{x_2}^2}{2}}\sqrt{\frac{2}{n}}}
\]</span></p>
<p>The numerator is the quantity of interest: the difference in sample means. It should make sense that the larger the difference in sample means, the greater the probability that the difference will be statistically significant. However, considering only the sample means <span class="math inline">\(\bar{x_1}\)</span> and <span class="math inline">\(\bar{x_2}\)</span> is not enough. We also need to account for variation within each sample, and for the total sample size. Variance should <em>decrease</em> <em>t</em>, while sample size should increase it. Both terms are put in the denominator so that the difference in means is relative to them. Notice that in the denominator, the variances <span class="math inline">\(s_{x_1}^1\)</span> and <span class="math inline">\(s_{x_2}^1\)</span> are in a numerator. Thus, increasing them will decrease <em>t</em>. On the other hand, the sample size <em>n</em> is in a numerator in the denominator (which is tantamount to being in the overall numerator). Thus, increasing sample size will increase <em>t</em>.</p>
<p>But as elegant as Student’s <em>t</em> is, it has some drawbacks. It can produce biased estimates and <em>p</em>-values when the two groups have unqual sample sizes, or unequal variances. For these reasons, a more modern version of the <em>t</em> statistic was developed by Welch in the 1940s. This is sometimes called the “Welch’s <em>t</em>-test”, or less precisely the “Welch-Satterthwaite <em>t</em>-test”. Satterthwaite’s contribution was not to the <em>t</em> statistic, but rather an equation to better calculate the degrees of freedom to use for the test<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
<p><span class="math display">\[
t=\frac{\bar{x_1}-\bar{x_2}}{\sqrt{\frac{s_1}{\sqrt{n_1}}+\frac{s_2}{\sqrt{n2}}}}
\]</span> This newer version has the same numerator, but instead of pooling the variances and sample sizes, keeps them separate. This allows for more flexibility when dealing with unequal sample sizes or (mildly) heteroscedastic data.</p>
</section>
<section id="sec-groups-more" class="level2" data-number="15.5">
<h2 data-number="15.5" class="anchored" data-anchor-id="sec-groups-more"><span class="header-section-number">15.5</span> Tests for 3 or more groups</h2>
<section id="sec-groups-more-anova" class="level3" data-number="15.5.1">
<h3 data-number="15.5.1" class="anchored" data-anchor-id="sec-groups-more-anova"><span class="header-section-number">15.5.1</span> Analysis of variance</h3>
<p>In this section, we will explore the “test comparing group means” sense of analysis of variance (ANOVA) (<a href="ch14.html#sec-review-lin-anova" class="quarto-xref"><span>Section 14.5</span></a>). The linear model version of ANOVA assesses significance using an <em>F</em>-test. Much like <em>t</em>, <em>F</em> is a test statistic that summarizes a quantity of interest in a test that can be compared to the typical strength of a pattern produced by random noise (see <a href="#sec-groups-2samp-2t" class="quarto-xref"><span>Section 15.2.1</span></a>}). Whereas <em>t</em> is usually a difference in means scaled by sample size and variance, <em>F</em> compares variances. The basic idea of an <em>F</em> statistic is:</p>
<p><span class="math display">\[F=\frac{\text{explained variance}}{\text{unexplained variance}}\]</span></p>
<p>In the case of a one-way ANOVA, this translates to:</p>
<p><span class="math display">\[F=\frac{\text{between-group variability}}{\text{within-group variability}}\]</span></p>
<p>The numerator is essentially the variance in group means:</p>
<p><span class="math display">\[\sum_{i=1}^Kn_i\frac{\left(\bar{Y}_{i}-\bar{Y}\right)^2}{\left(K-1\right)}\]</span></p>
<p>where <span class="math inline">\(\bar{Y}_{i}\)</span> is the sample mean in group <span class="math inline">\(i\)</span>, <span class="math inline">\(n_i\)</span> is the number of observations in group <span class="math inline">\(i\)</span>, <span class="math inline">\(\bar{Y}\)</span> is the overall mean of the data, and <span class="math inline">\(K\)</span> is the number of groups.</p>
<p>The denominator is close to the the sum of within-group variances:</p>
<p><span class="math display">\[
\frac{
\sum_{i=1}^K\sum_{j=1}^{n_i}
\left(Y_{ij}-\bar{Y}_i\right)^2
}{
N-K
}
\]</span></p>
<p>where <span class="math inline">\(Y_{ij}\)</span> is observation <span class="math inline">\(j\)</span> in group <span class="math inline">\(i\)</span> (out of <span class="math inline">\(K\)</span> groups), and <span class="math inline">\(N\)</span> is the overall sample size.</p>
<p>The <span class="math inline">\(F\)</span> statistic is a ratio of <em>variance explained</em> to <em>variance not explained</em>. <em>F</em> values follow the <em>F</em> distribution, which is defined by degrees of freedom <span class="math inline">\(d_1=K-1\)</span> and <span class="math inline">\(d_2=N-K\)</span> under the null hypothesis. Practically, <em>F</em> will be large when there is more explained variance than unexplained variance, which is unlikely if the group means are not different.</p>
<p><strong>Question:</strong> Do the means differ between groups (with number of groups <span class="math inline">\(\geq2\)</span>.</p>
<p><strong>Null hypothesis:</strong> All group means are equal.</p>
<p><strong>Alternative hypothesis:</strong> At least one group mean is different from the others.</p>
<p><strong>Example use case:</strong> Marge needs to test whether cucumber mass is greater in plants grown in potting mix, sandy soil, or clayey soil.</p>
<p>The nature of the <em>F</em> statistic belies the other meaning of ANOVA: the partitioning of variation into its different sources. In other words, what proportion of variation in the <em>Y</em> variable does each factor explain? How much variation is due to random chance (i.e., residual variation)? ANOVA in this sense can be applied to many models, including all linear models.</p>
<p>The first step in a typical ANOVA is the <strong>omnibus test</strong>, which assesses whether <em>any</em> of the group means differ from each other. Then, a <strong>post-hoc test</strong> is performed to check <em>which</em> groups differ from each other.</p>
<p>ANOVAs are typically described as “X-way ANOVA”, where X is the number of factors. For example, a test of mean stomach size in herbivorous, carnivorous, and omnivorous mammals would be a “one-way ANOVA” because it has one grouping variable, “diet”. The three groups in the factor diet are the <strong>levels</strong> of the factor.</p>
<section id="sec-groups-more-anova-1way" class="level4" data-number="15.5.1.1">
<h4 data-number="15.5.1.1" class="anchored" data-anchor-id="sec-groups-more-anova-1way"><span class="header-section-number">15.5.1.1</span> One-way ANOVA</h4>
<p>When there is one explanatory <strong>factor</strong>, or grouping variable, the test is called a <strong>one-way ANOVA</strong> regardless of how many <strong>levels</strong> or groups that factor contains. Here is an example using the built-in example dataset <code>iris</code>. There are two common ways to fit an ANOVA in R.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># method 1: lm()</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petal.Length<span class="sc">~</span>Species, <span class="at">data=</span>iris)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># method 2: aov()</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(Petal.Length<span class="sc">~</span>Species, <span class="at">data=</span>iris)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Once the model is fit, we request the <strong>anova table</strong> so we can see the contributions of each source of variation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># method 1: using lm</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Petal.Length
           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Species     2 437.10 218.551  1180.2 &lt; 2.2e-16 ***
Residuals 147  27.22   0.185                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># method 2: using aov</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
Species       2  437.1  218.55    1180 &lt;2e-16 ***
Residuals   147   27.2    0.19                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>No matter which method we use, the ANOVA table shows us that the factor <code>Species</code> uses 2 degrees of freedom (variously abbreviated as DF, Df, or d.f.) to account for 437.10 of the squared errors; the residuals use 147 d.f. to account for 27.22 of the squared errors. The ratio of the mean squared error per d.f. associated with each source, 218.551 / 0.185 = 1180.2, is the test statistic <em>F</em>. This is used to calculate the <em>P</em>-value (much like <em>t</em>, <em>F</em> follows a particular distribution defined by DF, which allows <span class="math inline">\(p(F)\)</span> to be calculated). We can also see that about 94.1% of variation (437.10 / (437.10+27.22)) is associated with species. This is the model’s coefficient of determination, or <span class="math inline">\(R^2\)</span>. The <span class="math inline">\(R^2\)</span> tells you the proportion of variation in <em>Y</em> explained by the model.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Rounding errors</strong></p>
<p>R is somewhat idiosyncratic in choosing how many digits it prints, and this can lead to confusion if values are rounded to too few decimal places. In the ANOVA example above, the MSE for the two sources of variation should divide to the F statistic. However, <span class="math inline">\(218.55/0.19\neq1180\)</span>. If you look at the raw output of <code>mod1</code>, however, you that the sums of squares for Species and Residuals are 437.1028 and 27.2226, respectively. With more decimal places, you can then recalculate <span class="math inline">\(\left(437.1028/2\right)/\left(27.2226/147\right)=1180.161\)</span>, the correct <span class="math inline">\(F\)</span> ratio.</p>
</div>
</div>
<p>Remember that the all that the omnibus test <em>p</em>-value tells you is that the means of at least one pair of species differ. To find out which pair or pairs, we need to use a post-hoc test. My favorite is the Tukey’s honest significant difference (HSD) test because it automatically adjusts for multiple comparisons.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># method 1:</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(<span class="fu">aov</span>(mod1))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = mod1)

$Species
                      diff     lwr     upr p adj
versicolor-setosa    2.798 2.59422 3.00178     0
virginica-setosa     4.090 3.88622 4.29378     0
virginica-versicolor 1.292 1.08822 1.49578     0</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># method 2:</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(mod2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Petal.Length ~ Species, data = iris)

$Species
                      diff     lwr     upr p adj
versicolor-setosa    2.798 2.59422 3.00178     0
virginica-setosa     4.090 3.88622 4.29378     0
virginica-versicolor 1.292 1.08822 1.49578     0</code></pre>
</div>
</div>
<p>The Tukey output shows us that every group differs from every other, with <em>p&lt;0.001</em> (here <em>p</em> is rounded to 0, although it can never be 0). The differences in group means are presented with their <strong>95% confidence intervals (CI)</strong>. For example, the difference between the group means of <code>versicolor</code> and <code>setosa</code> is 2.798 cm, with 95% CI = [2.594, 3.002]. The fact that the difference is <span class="math inline">\(&gt;0\)</span> means that the mean in <code>versicolor</code> is greater than the mean in <code>setosa</code>. If the difference was negative, then that would mean that the mean in <code>setosa</code> was greater.</p>
<p>Notice that none of these CI include 0: this suggests that a true difference of 0 between any two groups is very unlikely. Even without examining <em>p</em>-values, CI provide a useful way to evaluate both the direction and magnitude of differences.</p>
<p>One of the nice things about the Tukey HSD test is that the <em>p</em>-values are automatically adjusted for <strong>multiple comparisons</strong>, a phenomenon where the probability of a false positive goes up as a <a href="https://xkcd.com/882/">researcher performs more tests</a>, using a customized version of the probability distribution for the test statistic. This controls the <strong>family wise error rate</strong>, or total false positive probability for this set of three related tests.</p>
<p>As with a <em>t</em>-test, a boxplot is usually the best way to show the results of an ANOVA.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Petal.Length<span class="sc">~</span>Species, <span class="at">data=</span>iris, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">8</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-ttestboxplot2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Boxplot showing that petal length is greater in *Iris versicolor* than in *Iris setosa*, and greater still in *Iris virginica*.">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-ttestboxplot2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.1: Boxplot showing that petal length is greater in <em>Iris versicolor</em> than in <em>Iris setosa</em>, and greater still in <em>Iris virginica</em>.
</figcaption>
<div aria-describedby="fig-ttestboxplot2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ch15_files/figure-html/fig-ttestboxplot2-1.png" class="img-fluid figure-img" alt="Boxplot showing that petal length is greater in *Iris versicolor* than in *Iris setosa*, and greater still in *Iris virginica*." width="672">
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-groups-more-anova-ways" class="level4" data-number="15.5.1.2">
<h4 data-number="15.5.1.2" class="anchored" data-anchor-id="sec-groups-more-anova-ways"><span class="header-section-number">15.5.1.2</span> Two- or more way ANOVA</h4>
<p>When there are 2 or more explanatory factors, the test is called a <strong>two-way ANOVA</strong>, or <strong>three-way ANOVA</strong>, and so on. We can add additional factors to an ANOVA with the <code>+</code> sign.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make a copy of iris with an extra grouping variable</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>iris2 <span class="ot">&lt;-</span> iris</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>iris2<span class="sc">$</span>Flower <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"purple"</span>, <span class="st">"pink"</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="co"># fit the two-way ANOVA without interaction</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">aov</span>(Petal.Length<span class="sc">~</span>Species<span class="sc">+</span>Flower, <span class="at">data=</span>iris2)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq  F value Pr(&gt;F)    
Species       2  437.1  218.55 1174.229 &lt;2e-16 ***
Flower        1    0.0    0.05    0.261   0.61    
Residuals   146   27.2    0.19                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Adding the colors that way just repeated them until the column was full: purple, pink, purple, pink, and so on until the new vector had length 150 (the number of rows in <code>iris</code>). This essentially distributes the colors randomly with respect to the species and thus the petal lengths, so it should be no surprise that flower color had no effect on petal length (<span class="math inline">\(p=0.61\)</span>). A Tukey test confirms the effects of species, and the non-effect of <code>Flower</code>. Technically, you don’t need to do or report a Tukey test if the main effect is nonsignificant.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(mod3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Petal.Length ~ Species + Flower, data = iris2)

$Species
                      diff      lwr      upr p adj
versicolor-setosa    2.798 2.593692 3.002308     0
virginica-setosa     4.090 3.885692 4.294308     0
virginica-versicolor 1.292 1.087692 1.496308     0

$Flower
             diff        lwr       upr     p adj
purple-pink 0.036 -0.1032347 0.1752347 0.6101255</code></pre>
</div>
</div>
</section>
<section id="sec-groups-more-anova-inter" class="level4" data-number="15.5.1.3">
<h4 data-number="15.5.1.3" class="anchored" data-anchor-id="sec-groups-more-anova-inter"><span class="header-section-number">15.5.1.3</span> ANOVA with interaction</h4>
<p>Another important question is whether there is an <strong>interaction</strong> between two variables. An interaction is a situation where one variable changes the effect of another. To test for an interaction between two variables, use the <code>*</code> symbol instead of the <code>+</code>. The result <code>y~x1*x2</code> is shorthand for <code>y~x1+x2+x1:x2</code>. The individual effects of the variables <code>x1</code> and <code>x2</code> are called their <strong>main effects</strong>. The effect of both together <code>x1:x2</code> is the <strong>interaction effect</strong>. If a significant interaction effect is detected, then the main effects should not be interpreted by themselves.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit the two-way ANOVA WITH interaction</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">aov</span>(Petal.Length<span class="sc">~</span>Species<span class="sc">*</span>Flower, <span class="at">data=</span>iris2)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Df Sum Sq Mean Sq  F value Pr(&gt;F)    
Species          2  437.1  218.55 1161.375 &lt;2e-16 ***
Flower           1    0.0    0.05    0.258  0.612    
Species:Flower   2    0.1    0.04    0.201  0.818    
Residuals      144   27.1    0.19                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The interaction is nonsignificant, so we should instead report the main effects in the model without the interaction (<code>mod2</code>). If there is an interaction present, then it becomes impossible to discuss the effects of one variable without discussing the effects of the other. We will explore interactions more in the section on ANCOVA below.</p>
</section>
<section id="sec-groups-more-anova-block" class="level4" data-number="15.5.1.4">
<h4 data-number="15.5.1.4" class="anchored" data-anchor-id="sec-groups-more-anova-block"><span class="header-section-number">15.5.1.4</span> Blocking designs</h4>
<p><strong>Blocking</strong> is a strategy in experimental design that attempts to control for variation by grouping experimental units (observations) into groups called <strong>blocks</strong>. Blocks are defined by observations that are similar to each other in some attribute–like location, time, sex, species, etc.–that contributes to overall variation and that the researcher needs to control for.</p>
<p>Consider the example below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>Illustration of a field experiment with 3 researcher-applied treatments, A, B, and C, spread out over a landscape.</figcaption>
<p><img src="../images/review-blocking1.jpg" class="img-fluid figure-img" alt="Schematic of an unblocked experimental design with three treatments. Experimental units assigned to Treatment A, Treatment B, and Treatment C are represented by blue squares, orange triangles, and green circles, respectively. Units from all three treatments are distributed throughout the experimental area without being grouped into blocks."></p>
</figure>
</div>
<p>This experiment appears to have randomly distributed its treatments across space, which is good. However, there will still be variation among observations that is caused by different environments or habitats in different places. Rather than model those location-specific differences explicitly, the research could instead distributed <strong>blocks</strong> of observations randomly across space, with each block containing 1 observation of each of the 3 treatments.</p>
<p><img src="../images/review-blocking2.jpg" class="img-fluid" alt="Illustration of a field experiment with 3 researcher-applied treatments, A, B, and C, arranged in blocks spread out over a landscape.">{fig-alt=“fig-alt=”Schematic of a blocked experimental design with three treatments. Experimental units assigned to Treatment A, Treatment B, and Treatment C are represented by blue squares, orange triangles, and green circles, respectively. The units are arranged into nine blocks, shown as rectangles, with each block containing one unit from each treatment.”}</p>
<p>Now, variation attributable to spatial factors can be associated with the blocks and no longer confounds the effects of treatment. Observations within a block should be close enough that they experience the same environmental conditions.</p>
<p>In the example code below, we are going to add an imaginary factor to the <code>iris</code> dataset, <code>color</code>. The example analysis shows how a researcher would test for a difference in petal length between flowers of different colors, while accounting for the fact that different species have different petal lengths. In this analysis, the researcher is interested in differences between colors, and considers species a potential confounding variable.</p>
<p>This example works because we force the color effect with an artificial variable, and because the setup says explicitly that the researcher considers species a potential confound. From an experimental design standpoint, blocking is not synonymous with “a second categorical factor in an ANOVA”, although that is how it is treated mathematically.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># spare copy</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>dx <span class="ot">&lt;-</span> iris</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="co"># make the largest flowers within each species purple,</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="co"># and the smallest flowers blue. </span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="co"># scale within species</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">tapply</span>(dx<span class="sc">$</span>Petal.Length, dx<span class="sc">$</span>Species, scale)</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>dx<span class="sc">$</span>z <span class="ot">&lt;-</span> <span class="fu">do.call</span>(c, z)</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a><span class="co"># any flower &gt;= 0.6 SD away from mean</span></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a><span class="co"># is a non-white color</span></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>dx<span class="sc">$</span>color <span class="ot">&lt;-</span> <span class="st">"white"</span></span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>dx<span class="sc">$</span>color[<span class="fu">which</span>(dx<span class="sc">$</span>z <span class="sc">&lt;=</span> <span class="sc">-</span><span class="fl">0.6</span>)] <span class="ot">&lt;-</span> <span class="st">"blue"</span></span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>dx<span class="sc">$</span>color[<span class="fu">which</span>(dx<span class="sc">$</span>z <span class="sc">&gt;=</span> <span class="fl">0.6</span>)] <span class="ot">&lt;-</span> <span class="st">"purple"</span></span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a><span class="co"># vector of colors</span></span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"purple"</span>, <span class="st">"white"</span>)</span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Petal.Length<span class="sc">~</span>color, <span class="at">data=</span>dx, <span class="at">col=</span>cols)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch15_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The boxplot shows that the sample medians for blue, white, and purple are the smallest, intermediate, and greatest, respectively. But is that a significant difference?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># test for effect of color on petal length</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(Petal.Length<span class="sc">~</span>color, <span class="at">data=</span>dx))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)
color         2   13.6   6.805   2.219  0.112
Residuals   147  450.7   3.066               </code></pre>
</div>
</div>
<p>No, it’s not. But at this point the researcher should suspect that a lot of variation is size is really due to species. If she controls for species by treating it as a blocking factor, then she might be better able to detect an effect of color.</p>
<p>Below is the same petal length data broken up by color within species. Now, we can see that within each species, blue flowers are smaller and purple flower are larger. The first ANOVA couldn’t detect that because it didn’t consider species.</p>
<p>Also, note the use of <code>axis()</code> to create a more elegant set of labels for the x-axis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="fl">6.1</span>, <span class="fl">4.1</span>, <span class="fl">1.1</span>, <span class="fl">1.1</span>), <span class="at">bty=</span><span class="st">"n"</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Petal.Length<span class="sc">~</span>color<span class="sc">+</span>Species, <span class="at">data=</span>dx, <span class="at">col=</span>cols,</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">xaxt=</span><span class="st">"n"</span>, <span class="at">xlab=</span><span class="st">""</span>, <span class="at">ylab=</span><span class="st">"Petal length (cm)"</span>)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side=</span><span class="dv">1</span>, <span class="at">at=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">labels=</span>cols)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side=</span><span class="dv">1</span>, <span class="at">at=</span><span class="dv">4</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">labels=</span>cols)</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side=</span><span class="dv">1</span>, <span class="at">at=</span><span class="dv">7</span><span class="sc">:</span><span class="dv">9</span>, <span class="at">labels=</span>cols)</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side=</span><span class="dv">1</span>, <span class="at">at=</span><span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">8</span>), <span class="at">labels=</span><span class="fu">levels</span>(dx<span class="sc">$</span>Species), <span class="at">line=</span><span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch15_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Here is the ANOVA rerun with species as a blocking factor:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>anovatable <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">aov</span>(Petal.Length<span class="sc">~</span>color<span class="sc">+</span>Species, <span class="at">data=</span>dx))</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>anovatable</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
color         2   13.6    6.81   130.6 &lt;2e-16 ***
Species       2  443.2  221.58  4251.0 &lt;2e-16 ***
Residuals   145    7.6    0.05                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>This shows that there is a significant effect of color, after species has been accounted for. We can also see why species covered the effect of color: there are considerably more sums of squares associated with species than with color.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>anovatable[[<span class="dv">1</span>]][,<span class="dv">2</span>]<span class="sc">/</span><span class="fu">sum</span>(anovatable[[<span class="dv">1</span>]][,<span class="dv">2</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02931143 0.95441113 0.01627743</code></pre>
</div>
</div>
<p>The total variance is approximately <span class="math inline">\(13.61+443.16+7.56=464.33\)</span>. Most of that variance (<span class="math inline">\(100\left(443.16/464.33\right)\approx95.4\%\)</span>) is attributed to differences between species. Only about 3% (<span class="math inline">\(13.61/464.33\)</span>) is attributed to color. It’s a small effect, but a significant one, and only detectable after accounting for species.</p>
</section>
<section id="sec-groups-more-anova-rep" class="level4" data-number="15.5.1.5">
<h4 data-number="15.5.1.5" class="anchored" data-anchor-id="sec-groups-more-anova-rep"><span class="header-section-number">15.5.1.5</span> Repeated measures ANOVA</h4>
<p>Coming soon!</p>
</section>
</section>
<section id="sec-groups-more-kw" class="level3" data-number="15.5.2">
<h3 data-number="15.5.2" class="anchored" data-anchor-id="sec-groups-more-kw"><span class="header-section-number">15.5.2</span> Kruskal-Wallis test</h3>
<p><strong>Question:</strong> Are values in one or more groups consistently greater or less than values in another group? (number of groups <span class="math inline">\(\geq3\)</span>); essentially extends Wilcoxon test to more groups)</p>
<p><strong>Null hypothesis:</strong> For randomly selected values <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> from any 2 groups, <span class="math inline">\(p\left(x&gt;y\right)=p\left(y&gt;x\right)\)</span>.</p>
<p><strong>Alternative hypothesis:</strong> For randomly selected values <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> from any 2 groups, <span class="math inline">\(p\left(x&gt;y\right)\neq p\left(y&gt;x\right)\)</span></p>
<p><strong>Example use case:</strong> Bart is studying whether tomato yields tend to be greater in plants treated with no pesticide, pesticide A, or pesticide B. He is not interested in predicting the actual tomato yield.</p>
<p>Because ANOVA is a linear model, the data used in ANOVA must meet the <a href="@sec-review-lin-assum">assumptions of the linear model</a>. If the data do not meet the assumptions, or cannot be transformed to do so, then a nonparametric alternative to ANOVA is needed. The most common alternative is the <strong>Kruskal-Wallis test</strong>. Some texts refer to this as a “nonparametric ANOVA”, but this is not correct because at no point is variance actually partitioned. Like the Wilcoxon test, the Kruskal-Wallis test is based on ranks of the data. A significant Kruskal-Wallis test indicates that values in at least one group are consistently greater than values in at least one other group. As with ANOVA, a post-hoc test is needed to determine which groups differ significantly from each other.</p>
<p><strong>Example Kruskal-Wallis test in R</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(Petal.Length<span class="sc">~</span>Species, <span class="at">data=</span>iris)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  Petal.Length by Species
Kruskal-Wallis chi-squared = 130.41, df = 2, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The significant result means that petal length is consistently greater for at least species compared to the other. This is analogous to the omnibus ANOVA test. If we want to know which groups differ, we need a post-hoc test. The most common option is the Dunn’s test.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dunn.test)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dunn.test</span>(iris<span class="sc">$</span>Petal.Length, iris<span class="sc">$</span>Species, <span class="at">method=</span><span class="st">"bonferroni"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Kruskal-Wallis rank sum test

data: x and group
Kruskal-Wallis chi-squared = 130.411, df = 2, p-value = 0

                           Comparison of x by group                            
                                 (Bonferroni)                                  
Col Mean-|
Row Mean |     setosa   versicol
---------+----------------------
versicol |  -5.862996
         |    0.0000*
         |
virginic |  -11.41838  -5.555388
         |    0.0000*    0.0000*

alpha = 0.05
Reject Ho if p &lt;= alpha/2</code></pre>
</div>
</div>
<p>Interpretation: A posthoc Dunn’s test showed that all three species differed from each other in terms of the rank order of petal lengths.</p>
</section>
</section>
<section id="sec-groups-ord" class="level2" data-number="15.6">
<h2 data-number="15.6" class="anchored" data-anchor-id="sec-groups-ord"><span class="header-section-number">15.6</span> Tests with ordered factors</h2>
<p>Some factors can represent group membership, but still have an inherent ordering to them. For example, soft drinks come in sizes “small”, “medium”, and “large”. These are categories, but categories in order: small &lt; medium &lt; large. In contrast, the three species in the <code>iris</code> dataset have no ordering.</p>
<p>You may have data with a factor for age, like “juvenile”, “subadult”, “adult”. These categories correspond to ages, but cannot be treated as literal numbers of years or months. It would also be a mistake to treat the comparison of “juvenile vs.&nbsp;subadult” the same as the comparison of “juvenile vs.&nbsp;adult”.</p>
<p>If you analyze an ordered factor, R will estimate polynomial terms of order up to <span class="math inline">\(k-1\)</span>, where <span class="math inline">\(k\)</span> is the number of factor levels. The polynomial function is a way to fit different patterns across the ordered levels. For example, a linear pattern captures a monotonic increase or decrease across the levels. A quadratic pattern can describe a situation where the middle of three levels has greater (or smaller) values than the first and third levels. Let’s create a toy dataset to illustrate working with an ordered factor.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>ages <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"juvenile"</span>, <span class="st">"subadult"</span>, <span class="st">"adult"</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>dx <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">age=</span><span class="fu">rep</span>(ages, <span class="at">each=</span><span class="dv">20</span>))</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="co"># tell R that this is an ordered factor</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>dx<span class="sc">$</span>age <span class="ot">&lt;-</span> <span class="fu">factor</span>(dx<span class="sc">$</span>age, <span class="at">levels=</span>ages, <span class="at">ordered=</span><span class="cn">TRUE</span>)</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a><span class="co"># notice the levels statement:</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>dx<span class="sc">$</span>age</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] juvenile juvenile juvenile juvenile juvenile juvenile juvenile juvenile
 [9] juvenile juvenile juvenile juvenile juvenile juvenile juvenile juvenile
[17] juvenile juvenile juvenile juvenile subadult subadult subadult subadult
[25] subadult subadult subadult subadult subadult subadult subadult subadult
[33] subadult subadult subadult subadult subadult subadult subadult subadult
[41] adult    adult    adult    adult    adult    adult    adult    adult   
[49] adult    adult    adult    adult    adult    adult    adult    adult   
[57] adult    adult    adult    adult   
Levels: juvenile &lt; subadult &lt; adult</code></pre>
</div>
</div>
<p>Here we use our new factor to plot and analyze french fry consumption across age categories:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add y values</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>dx<span class="sc">$</span>ff <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>dx<span class="sc">$</span>ff[<span class="fu">which</span>(dx<span class="sc">$</span>age<span class="sc">==</span><span class="st">"juvenile"</span>)] <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="dv">5</span>, <span class="dv">1</span>)</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>dx<span class="sc">$</span>ff[<span class="fu">which</span>(dx<span class="sc">$</span>age<span class="sc">==</span><span class="st">"subadult"</span>)] <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="dv">15</span>, <span class="dv">1</span>)</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>dx<span class="sc">$</span>ff[<span class="fu">which</span>(dx<span class="sc">$</span>age<span class="sc">==</span><span class="st">"adult"</span>)] <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="dv">10</span>, <span class="dv">1</span>)</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect the data</span></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(ff<span class="sc">~</span>age, <span class="at">data=</span>dx, <span class="at">ylab=</span><span class="st">"French fry consumption"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-ttestboxplot3" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Boxplot showing that french fry consumption is greatest in subadults, less in adults, and lowest in juveniles.">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-ttestboxplot3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15.2: Boxplot showing that french fry consumption is greatest in subadults, less in adults, and lowest in juveniles.
</figcaption>
<div aria-describedby="fig-ttestboxplot3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ch15_files/figure-html/fig-ttestboxplot3-1.png" class="img-fluid figure-img" alt="Boxplot showing that french fry consumption is greatest in subadults, less in adults, and lowest in juveniles." width="672">
</div>
</figure>
</div>
</div>
</div>
<p>Now fit the model using the ordered factor <code>age</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>mod11 <span class="ot">&lt;-</span> <span class="fu">aov</span>(ff<span class="sc">~</span>age, <span class="at">data=</span>dx)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod11)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)    
age          2 1008.8   504.4   526.2 &lt;2e-16 ***
Residuals   57   54.6     1.0                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The omnibus test shows us that <code>age</code> is significant. However, because we have an ordered factor, we don’t want something like a Tukey test. Group means are not of interest; rather, the pattern in group means across groups is. So, we what we want is to see which patterns across <code>age</code> are significant.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary.lm</span>(mod11)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
aov(formula = ff ~ age, data = dx)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.88500 -0.78190 -0.08528  0.59410  2.17546 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   9.9419     0.1264   78.66   &lt;2e-16 ***
age.L         3.6275     0.2189   16.57   &lt;2e-16 ***
age.Q        -6.1060     0.2189  -27.89   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9791 on 57 degrees of freedom
Multiple R-squared:  0.9486,    Adjusted R-squared:  0.9468 
F-statistic: 526.2 on 2 and 57 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The coefficients for <code>age.L</code> and <code>age.Q</code> are the linear and quadratic trends, respectively. In this case, there is a positive linear trend (<code>3.5113</code>), so <span class="math inline">\(Y\)</span> generally increases with age category. There is also a significant negative quadratic trend (<code>-6.2328</code>), meaning that the relationship is curved. These trends describe the <em>shape</em> of the trend with respect to the age categories, not literally the values of <span class="math inline">\(Y\)</span> given <span class="math inline">\(X\)</span> (as in a polynomial equation), so you need to inspect the boxplot or a plot of means.</p>
<p>This analysis was simple because there were only 3 levels of <code>age</code>. When an ordered factor has many levels, you may observe “significant” polynomial trends that are biologically unimportant or difficult to interpret. It is up to you as a biologist to exercise some judgement in deciding how many terms to interpret. For example, a quadratic pattern can be readily interpreted biologically. But what about a quintic? Or an octic?</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Gosset published his work under the pen name “Student” because his employer at the time, the Guinness Brewery, didn’t want their competitors to know that they used the <em>t</em>-test in their quality control procedures.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This is why <em>t</em>-tests in R often report non-integer degrees of freedom.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/greenquanteco\.github\.io\/appl-biol-data-analysis\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/ch14.html" class="pagination-link" aria-label="Introductory statistics with R">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Introductory statistics with R</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/ch16.html" class="pagination-link" aria-label="Tests for continous patterns">
        <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Tests for continous patterns</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/greenquanteco/appl-biol-data-analysis/edit/main/chapters/ch15.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/greenquanteco/appl-biol-data-analysis/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>