{
  "hash": "3b3225dcaab164d51b2740c20de18e12",
  "result": {
    "engine": "knitr",
    "markdown": "# Tests for differences in mean or location {#sec-groups}\n\nIn a test for difference in mean or location, we are interested in\nwhether observations differ between groups. Most of the time we are testing whether the central tendency differs between groups. A test of this kind evaluates a prediction like, \"a typical value in group A is different from a typical value in group B\".\n\nAlternatively, we can test for a difference in **location**: the\nrelative position of random values from 2 or more groups. This is a\nslightly different statement: \"values in group A tend to be greater than\n(or less than) values in group B\". Put another way: \"If we pick a random\nvalue from group A, it will be reliably greater (or less than) than a\nrandom value from group B\". Tests for location are performed on the **rank order** of the values, not the values themselves.\n\nWhen comparing groups, the data are usually best shown using a\n**boxplot**, also known as a **box-and-whiskers** plot. The exact\nimplementation varies between software packages, but boxplots usually\nshow the median, interquartile range (approximately), extreme values,\nand possible outliers (if any) Run the command `?boxplot.stats` to see a description of how boxplots are calculated in R.\n\n## Tests for 1 group {#sec-groups-1samp}\n\nWhen all of the values come from the same set of observations, we can\nask questions such as:\n\n- Is the mean in this group equal to, or different from, some arbitrary value?\n- Is the mean in this group greater than, or not greater than, some arbitrary value?\n\nThese questions are the domain of **one-sample tests**. The most important is the **one-sample *t*-test**, which comes in two varieties: **one-tailed** and **two-tailed**. All one-sample tests compare the mean of a set of values to some quantity (hypothetical mean) of interest, called $\\mu$ (the Greek letter \"mu\"). In a one-tailed test, the null hypothesis is that the underlying population mean is either $\\le\\mu$ or $\\ge\\mu$. In a two-tailed test, the null hypothesis is that the population mean is equal to $\\mu$.\n\n:::{.tip}\n**A note on symbology: sample vs. population parameters**\n\nIn statistics, we analyze **samples** (randomly-selected subsets of\nobserved entities) to make inferences about **populations** (the\nhypothetical set of all possible entities which could be included in a\nsample). For example, if you wanted to know how the population of a\nnation of 100 million citizens felt about some political issue, it would\nbe time-consuming and expensive to ask each citizen what they thought.\nInstead, you would sample a randomly selected set of 1000 citizens\nand then assume that those results reflected the opinion of the entire\ncitizenry. For this assumption to work, your sample must be both random\nand representative of the entire population.\n\nSimilarly, in science we cannot collect a infinite amount of data, or\nmeasure every squirrel in the forest, or any other type of exhaustive\nand comprehensive data collection. We instead take representative\nsamples of all the possible samples–i.e., the population–and rely on\ngood practices in experimental design to enable us to assume that our\nsample represents the population.\n\nThe reason I bring this up here is that we need to keep in mind the\ndifference between sample statistics and population statistics. **Sample\nstatistics** are calculated from your data. **Population statistics**\nare **inferred** from your data using statistical models. This is why\nstatistical tests are commonly referred to as **inferential\nstatistics**, and why simple calculations from data are referred to as\n**descriptive statistics**.\n\nThe most common descriptive statistics are shown below:\n\n| Parameter          |  Sample   |  Population  |\n|--------------------|:---------:|:------------:|\n| Mean               | $\\bar{x}$ |    $\\mu$     |\n| Variance           |  $s^{2}$  | $\\sigma^{2}$ |\n| Standard deviation |    $s$    |   $\\sigma$   |\n:::\n\n\n### One-sample, one-tailed *t*-test {#sec-groups-1samp-1t}\n\nIn a one-tailed one-sample test, we are interested in whether the\nunderlying population mean ($\\mu$) of a set of values is not equal to\nsome value of interest...either at most some value, or at least some\nvalue.\n\n**Question:** Is the mean value less than OR greater than some value\n$x$?\n\n**Null hypothesis:** True mean is $=x$.\n\n**Alternative hypothesis:** True mean is $<x$ or true mean is $>x$.\n\n**Example use case:**Fred needs to check whether the mean measurement\nerror across his 12 technicians is less than 0.5 mm.\n\nHere is an example where we simulate some data in R and run a one-tailed\none-sample *t*-test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# simulate some values with nominal mean 5 and sd 3\nset.seed(123)\na <- rnorm(20, 5, 3)\n\n# 1 sample 1 tailed t-test\n# Example 1: Is the underlying mean <= 0?\nt.test(a, alternative=\"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  a\nt = 8.3142, df = 19, p-value = 4.707e-08\nalternative hypothesis: true mean is greater than 0\n95 percent confidence interval:\n 4.29664     Inf\nsample estimates:\nmean of x \n 5.424871 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Example 2: Is the underlying mean <= 4?\nt.test(a, alternative=\"greater\", mu=4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  a\nt = 2.1838, df = 19, p-value = 0.02086\nalternative hypothesis: true mean is greater than 4\n95 percent confidence interval:\n 4.29664     Inf\nsample estimates:\nmean of x \n 5.424871 \n```\n\n\n:::\n:::\n\n\nInterpretation: In the example above, the researcher can reject the null\nhypothesis that the true mean is $\\leq4$, and conclude that the true\nmean is $>4$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Example 3: Is the underlying mean >= 5.5?\nt.test(a, alternative=\"less\", mu=5.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  a\nt = -0.11514, df = 19, p-value = 0.4548\nalternative hypothesis: true mean is less than 5.5\n95 percent confidence interval:\n     -Inf 6.553102\nsample estimates:\nmean of x \n 5.424871 \n```\n\n\n:::\n:::\n\n\nInterpretation: In example 3, the researcher cannot reject the null\nhypothesis that $\\mu\\geq5.5$. This makes sense, because the true mean is\nabout $5.4\\pm2.9$ (verify with `mean(a);sd(a)`).\n\n\n### One-sample, two-tailed *t*-test {#sec-groups-1samp-2t}\n\nIn a two-tailed test, we are interested in whether the underlying\npopulation mean of a set of values is **equal** to some value of\ninterest.\n\n**Question:** Is the underlying true mean equal to, or different from,\nsome value $\\mu$?\n\n**Null hypothesis:** True mean $=\\mu$.\n\n**Alternative hypothesis:** True mean $\\neq\\mu$\n\n**Example use case:** Wilma needs to test whether the mean pH of her\nprepared stock solution is equal to, or different from, the target pH of\n7.7.\n\nHere is an example where we simulate some data and conduct a one-sample,\ntwo-tailed *t*-test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# simulate data\nset.seed(123)\na <- rnorm(20, 3, 1)\n\n# 1 sample 2-tailed t-test:\n## Example 1: mu = 0 (default)\nt.test(a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  a\nt = 14.445, df = 19, p-value = 1.067e-11\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 2.686402 3.596845\nsample estimates:\nmean of x \n 3.141624 \n```\n\n\n:::\n:::\n\n\nInterpretation: In the example above, the researcher can reject the null\nthat the true mean = 0, and conclude that the true mean is significantly\ndifferent from 0.\n\nHere's another example with a different dataset and test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# simulate data\nset.seed(123)\na <- rnorm(20, 3, 1)\n\n# 1 sample 2-tailed t-test:\n## Example 2: mu = 5\nt.test(a, mu=5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  a\nt = -8.5445, df = 19, p-value = 6.218e-08\nalternative hypothesis: true mean is not equal to 5\n95 percent confidence interval:\n 2.686402 3.596845\nsample estimates:\nmean of x \n 3.141624 \n```\n\n\n:::\n:::\n\n\nInterpretation: The researcher can reject the null hypothesis that the\nmean = 5, and conclude that the true mean is not 5. Note that this\nincludes both $<5$ and $>5$ as possibilities, but the direction is obvious\nfrom the sample mean.\n\n## Tests for 2 groups {#sec-groups-2samp}\n\n### Student's *t*-test (Welch) (2-tail, 2-sample) {#sec-groups-2samp-2t}\n\nWhen most people say “*t*-test”, what they usually mean is a two-sample,\ntwo-tailed *t*-test that tests for a **difference in means between two\ngroups**. The original version was introduced as the\n**Student’s *t*-test** by William Sealy Gosset in 1908[^gosset];\nmodern software uses a modified version called the **Welch *t*-test**\n(or sometimes the “**Welch-Satterthwaite *t*-test**”, but this is not\nquite correct). The newer version is better at accounting for\nnon-normality and unequal variances.\n\n[^gosset]: Gosset published his work under the pen name “Student” because his employer at the time, the Guinness Brewery, didn’t want their competitors to know that they used the *t*-test in their quality control procedures.\n\nThe test statistic, *t*, is basically the difference in sample means scaled by the variance in each group and the sample size in each group. It is calculated as:\n\n$$\nt = \\frac{\\bar{x}_1-\\bar{x}_2}\n{\\sqrt{\\frac{s_1^2}{n_1}+\\frac{s_2^2}{n_2}}}\n$$\n\nwhere $\\bar{x_1}$ and $\\bar{x_2}$ are the sample means, $s_1^2$ and $s_2^2$ are the sample variances, and $n_1$ and $n_2$ are the sample sizes. Think through that equation...what would increasing the difference in means (the numerator) do to *t*? What about increasing one or both sample sizes? One or both sample variances?\n\nBasically, the numerator of *t* is the quantity of interest: the difference in means between two groups. The denominator is the standard error (SE) of that estimate.\n\nA *t* value by itself doesn't tell you much, though, because what we're interested in is how likely that *t* score is relative to the number of degrees of freedom (DF) in the dataset. While the early users would simply use *n-1* as the DF, modern *t*-statistics and *t* distributions are defined by a newer version of the degrees of freedom calculation:\n\n$$\ndf =\n\\frac{\n\\left(\n\\frac{s_1^2}{n_1}+\\frac{s_2^2}{n_2}\n\\right)^2\n}{\n\\frac{\\left(s_1^2/n_1\\right)^2}{n_1-1}\n+\n\\frac{\\left(s_2^2/n_2\\right)^2}{n_2-1}\n}\n$$\n\nSay you perform a test comparing groups A and B, and the *t* statistic comes out to be 1.95. We have to compare that to the *t* distribution with the number of DF contained in the data, which might be 31.2:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ch15_files/figure-pdf/unnamed-chunk-6-1.pdf)\n:::\n:::\n\n\nThe question for the hypothesis test is: in a dataset with 31.2 DF, how often should we observe *t* values at least as large as 1.95 (i.e., $\\left|t\\right|\\ge1.95$)? That proportion is the area shaded below:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ch15_files/figure-pdf/unnamed-chunk-7-1.pdf)\n:::\n:::\n\n\nThe area of the left shaded area is `pt(-1.95, 31.2)`, which is `0.0301`. The distribution is symmetrical, so $p\\left(\\left|t\\right|\\ge1.95\\right)=0.0301\\times2=0.0602$. Thus, the test was not significant (*t* = 1.95, 31.2 d.f., *p* = 0.06).\n\n**Question:** Do two groups have the same underlying population mean?\n\n**Null hypothesis:** The true difference in means = 0. I.e.,\n$\\mu_1=\\mu_2$.\n\n**Alternative hypothesis:** True difference in means is $\\neq0$. I.e.,\n$\\mu_1\\neq\\mu_2$.\n\n**Example use case:** Barney needs to test whether tomato plants treated\nwith a new pesticide have a different yield (g tomato / plant) than\nplants in the untreated control group.\n\nBelow is an example where we simulate some data and run a two-sample,\ntwo-tailed test to compare the means of two groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# simulate data\nset.seed(42)\na <- rnorm(100, 5, 2)\nb <- rnorm(100, 3, 2)\n\n# example 1: difference in means\nt.test(a,b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  a and b\nt = 8.1211, df = 194.18, p-value = 5.241e-14\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n 1.696004 2.783990\nsample estimates:\nmean of x mean of y \n 5.065030  2.825033 \n```\n\n\n:::\n:::\n\n\nInterpretation: The researcher should conclude that there is a\nstatistically significant difference between the means of groups a and\nb. In a manuscript, you should report the test statistic, the DF, and\nthe *p*-value. E.g., \"There was a significant difference in means\nbetween group a and group b ($t=8.121$, 194.18 d.f., $p<0.001$).\" Notice\nthat values are rounded to 2 or 3 decimal places, which is usually\nenough for biology. This is especially true for the *p*-value, which can\nbe approximated by R down to infinitesimally small values. I always\nround those to 0.001 or 0.0001.\n\nA *t*-test can also be performed using the **formula** interface, which\nis an R programming construct for specifying a response variable and its\npredictors. Notice that the formula interface here is the same as used in `boxplot()` (@sec-plot1-sing-box) and `aggregate()` (@sec-summ-agg).\n\n**Syntax note:** Formula syntax has the response variable on the left,\nthen a `~`, then the predictor or predictors. For predictors, `a + b`\nmeans an additive model; while `a * b` specifies an interaction. For a\n*t*-test, there can be only 1 predictor. If you want to test $>1$\npredictor at a time, you need to use ANOVA instead.\n\nHere are some common formula examples:\n\n| Formula | Meaning |\n|---|---|\n| `y ~ x` | `y` is modeled as a function of `x`. |\n| `y ~ x1 + x2` | `y` is modeled as a function of `x1` and `x2`, with their effects treated as **additive** (i.e., no interaction between them is included). |\n| `y ~ x1 * x2` | `y` is modeled as a function of `x1`, `x2`, and their **interaction**. An interaction means that the effect of one predictor depends on the value of the other predictor. This is shorthand for `y~x1 + x2 + x1:x2`. |\n| `y ~ 1` | `y` is modeled using only a constant (the intercept), with no predictors. This is often called an **intercept-only** or **null model**. |\n| `y ~ 0 + x` | `y` is modeled as a function of `x`, but without an intercept (i.e., the intercept is constrained to 0). |\n\n: Common R model formulas and their meanings. {#tbl-model-formulas}\n\nThe formula interface is used in several contexts in R, including\nplotting, modeling, and aggregating.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# pull some data from example dataset iris\n# i.e., make a new data frame with only 2 groups\ndx <- iris[which(iris$Species %in% c(\"setosa\", \"versicolor\")),]\n\n# perform the test.\nt.test(Petal.Length~Species, data=dx)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  Petal.Length by Species\nt = -39.493, df = 62.14, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group setosa and group versicolor is not equal to 0\n95 percent confidence interval:\n -2.939618 -2.656382\nsample estimates:\n    mean in group setosa mean in group versicolor \n                   1.462                    4.260 \n```\n\n\n:::\n:::\n\n\nInterpretation: The researcher should conclude that there is a\nstatistically significant difference between the mean petal length of\n*Iris setosa* and *Iris versicolor*.\n\n### Two-sample, one-tailed *t*-tests {#sec-groups-2samp-1t}\n\n**Question:** Is the true difference in means between 2 groups greater\nthan, or less than, some target value $\\mu$?\n\n**Null hypothesis:** The true difference in means between 2 groups is\n$\\mu$. I.e., $\\mu_1-\\mu_2=\\mu$.\n\n**Alternative hypothesis:** The true difference in means between 2\ngroups is either greater than $>\\mu$ or $<\\mu$. I.e., either\n$\\mu_1-\\mu_2>\\mu$ or $\\mu_1-\\mu_2<\\mu$.\n\n**Example use case:** Betty needs to compare two stock solutions and\ncheck that their pH differs by no more than 0.2.\n\nThe 2-sample, 1-tailed *t*-test that can be used in several ways:\n\n1.  Test whether the mean in one group is greater or less than the mean\n    in another group.\n2.  Test whether the the mean in one group is greater or less than the\n    mean in another group, and that the difference is at least some\n    specified value.\n\nFor example, if you know that the mean of group 1 must be less than the\nmean in group 2, and will not even consider that the mean of group 2 is\nless than that of group 1, then you could run a 2-sample 1-tailed test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# simulate data\nset.seed(789)\nx1 <- rnorm(20, 10, 1)\nx2 <- rnorm(20, 12, 1)\n\n# is mean(x1) > mean(x2)?\nt.test(x1, x2, alternative=\"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  x1 and x2\nt = -8.8728, df = 37.99, p-value = 1\nalternative hypothesis: true difference in means is greater than 0\n95 percent confidence interval:\n -2.402592       Inf\nsample estimates:\nmean of x mean of y \n 9.689982 11.708940 \n```\n\n\n:::\n\n```{.r .cell-code}\n# is mean(x1) < mean(x2)?\nt.test(x1, x2, alternative=\"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  x1 and x2\nt = -8.8728, df = 37.99, p-value = 4.259e-11\nalternative hypothesis: true difference in means is less than 0\n95 percent confidence interval:\n      -Inf -1.635323\nsample estimates:\nmean of x mean of y \n 9.689982 11.708940 \n```\n\n\n:::\n\n```{.r .cell-code}\n# is mean(x1) - mean(x2) at least 1?\nt.test(x1, x2, alternative=\"greater\", mu=1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  x1 and x2\nt = -13.267, df = 37.99, p-value = 1\nalternative hypothesis: true difference in means is greater than 1\n95 percent confidence interval:\n -2.402592       Inf\nsample estimates:\nmean of x mean of y \n 9.689982 11.708940 \n```\n\n\n:::\n\n```{.r .cell-code}\n# is mean(x1) - mean(x2) at most 1?\nt.test(x1, x2, alternative=\"less\", mu=1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  x1 and x2\nt = -13.267, df = 37.99, p-value = 3.867e-16\nalternative hypothesis: true difference in means is less than 1\n95 percent confidence interval:\n      -Inf -1.635323\nsample estimates:\nmean of x mean of y \n 9.689982 11.708940 \n```\n\n\n:::\n:::\n\n\nan uncommon variant used to test whether two groups have a difference in\nmeans that is less than or greater than some specified value. For\nexample, if you produce two batches of bacteria by inoculation,\nincubation, and then serial dilution, you may want to confirm that the\ndifference in cell count between them is less than some acceptable\nvalue. You could use a 2-sample, 1-tailed test with the \"alternative\"\nhypothesis being that the difference is \"greater\" than your benchmark.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(789)\nx1 <- rnorm(30, 5, 2)\nx2 <- rnorm(30, 5.5, 2)\n\n# is the true difference in means <1?\nt.test(x1, x2, alternative=\"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  x1 and x2\nt = -2.6676, df = 50.08, p-value = 0.9949\nalternative hypothesis: true difference in means is greater than 0\n95 percent confidence interval:\n -2.048126       Inf\nsample estimates:\nmean of x mean of y \n 4.438104  5.696001 \n```\n\n\n:::\n:::\n\n\n### Equivalence testing {#sec-groups-1samp-tost}\n\nIt is not possible to demonstrate statistically that a difference in\nmeans is truly 0, or that the underlying mean of a set of data truly is equal to a target value $\\mu$ (the converse of a one-sample, two-tailed *t*-test). With a 1-sample, 2-tailed test the best you can do is\n“fail to reject” the null hypothesis that the mean is 0. However, we can\nshow that the difference is arbitrarily close to 0. This approach is\ncalled **equivalence testing**, and one method is the **two one-sided\ntests** (**TOST**) method. The method works like this:\n\n![Illustration of the two one-sided test (TOST) strategy for establishing that a sample, or set of differences, has an underlying mean arbitrarily close to some value $\\mu$ ($\\mu=0$ in this example.)  ](../images/review-03.jpg)\n\nHere is a worked TOST equivalence test example in R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# simulate data\nset.seed(42)\na <- rnorm(100, 5, 1)\nb <- rnorm(100, 5, 1)\n\n# let target tolerance = 1\n# note that total tolerance range is 1, so\n# amount for both one-sided tests is 1/2==0.5\nD <- 0.5\n\n# test 1: is difference >-D?\nt.test(a, b, alternative = \"greater\", mu=-D)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  a and b\nt = 4.4956, df = 194.18, p-value = 5.955e-06\nalternative hypothesis: true difference in means is greater than -0.5\n95 percent confidence interval:\n -0.1079329        Inf\nsample estimates:\nmean of x mean of y \n 5.032515  4.912516 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# test 2: is difference <D?\nt.test(a, b, alternative = \"less\", mu=D)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  a and b\nt = -2.7554, df = 194.18, p-value = 0.00321\nalternative hypothesis: true difference in means is less than 0.5\n95 percent confidence interval:\n    -Inf 0.34793\nsample estimates:\nmean of x mean of y \n 5.032515  4.912516 \n```\n\n\n:::\n:::\n\n\nInterpretation: Test 1 showed that the difference in means is $>-0.5$.\nTest 2 showed that the difference in means is $<0.5$. So, the difference\nin means is in the interval $\\left(-0.5,0.5\\right)$, which means the difference in means is at most 0.5 in either direction.\n\n### Wilcoxon rank-sum test {#sec-groups-2samp-wilcoxon}\n\n**Question:** Are values in one group consistently greater than or less than those in another group? OR: Is the median rank in one group\ndifferent from that in another group?\n\n**Null hypothesis:** For randomly selected values $x$ and $y$ from two\ngroups, $p\\left(x>y\\right)=p\\left(y>x\\right)$.\n\n**Alternative hypothesis:** For randomly selected values X and Y from\ntwo groups, $p\\left(x>y\\right)\\neq p\\left(y>x\\right)$.\n\n**Example use case:** Homer is interested in whether plots where\ninvasive plants have been removed have more squirrels than plots where\ninvasive plants are not removed, but does not want to model the actual\nnumber of squirrels.\n\nThe **Mann-Whitney *U* test**, also known as the **Wilcoxon test**, is a\nnonparametric alternative to the two-sample *t*-test. **Nonparametric**\nmeans that the test does not make restrictive assumptions about the\ndistribution of the data or a test statistic. Nonparametric tests are\noften based on the **ranks** of the data: the smallest value is rank 1,\nthe next smallest is rank 2, and so on. Because of this, nonparametric\ntests allow you make statements about how consistent a pattern is,\nrather than about the actual values.\n\nThis test has two common use cases:\n\n-   The researcher is only interested in whether values in one group are\n    consistently larger than those in another group.\n\n-   The researcher needs to perform a *t*-test, but the data do not meet\n    the assumptions of the *t*-test.\n\nThe syntax for the Wilcoxon test is fairly similar to that of a\n*t*-test.\n\nExample Wilcoxon test in R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# simulate some data:\nset.seed(123)\na <- runif(20, 1, 6)\nb <- runif(20, 4, 9)\n\n# run the test\nwilcox.test(a,b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum exact test\n\ndata:  a and b\nW = 35, p-value = 1.126e-06\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\nHere is the same kind of test, but using the formula interface. You can\nuse the formula interface for *t*-tests as well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# pull some data from example dataset iris\n# i.e., make a new data frame with only 2 groups\nuse.species <- c(\"versicolor\", \"virginica\")\ndx <- iris[which(iris$Species %in% use.species),]\ndx$Species <- factor(dx$Species, levels=use.species)\n\n# perform the test.\nwilcox.test(Petal.Length~Species, data=dx)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  Petal.Length by Species\nW = 44.5, p-value < 2.2e-16\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\nInterpretation: The researcher can say that values in one group are\nconsistently greater than values in the other group. Which way that goes\nshould be obvious from looking at the sample medians or a boxplot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# follow up the test with a boxplot\n# note that the formula interface is used here as well!\nboxplot(Petal.Length~Species, data=dx)\n```\n\n::: {.cell-output-display}\n![](ch15_files/figure-pdf/unnamed-chunk-16-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nWhen sample sizes or effect sizes are large, the Wilcoxon test and the\n*t*-test will often give the same answers in terms of significance vs.\nnonsignificance.\n\nBecause the *t*-test tests for a difference in means, and the Wilcoxon\nis its rank-based alternative, some people think that the Wilcoxon test\nis a test for a difference in medians…but this is **not correct**. It’s\nmore accurate to say that the Wilcoxon test tests for a median\ndifference.\n\n## Tests for paired data {#sec-groups-paired}\n\n### Paired *t*-test {#sec-groups-paired-pt}\n\n**Question:** Is the mean of the differences of paired observations = 0,\nor different from 0?\n\n**Null hypothesis:** Mean of pairwise differences = 0.\n\n**Alternative hypothesis:** Mean of pairwise differences $\\neq0$.\n\n**Example use case:** Pebbles needs to test for a mean change in the\nbody mass of individual mice before and after a feeding trial. Each\nmouse is weighed both before and after the trial.\n\nMany biological experiments involved **paired samples**, where a single\nunit or entity was measured twice. For example, a single mouse might be\nweighed before and after a feeding trial. In a **paired *t*-test**, we\ntest whether or not the mean of differences is 0. This is subtly\ndifferent than the test for differences in means evaluated in a\ntwo-sample test. Consequently, a paired *t*-test is tantamount to a\none-sample test on the pairwise differences. Compare the null hypotheses\ntested by the two-sample *t*-test and paired *t*-test below:\n\n**Two-sample *t*-test:**\n$\\frac{\\sum_{i=1}^{n_1}x_{1,i}}{n_1}=\\frac{\\sum_{i=1}^{n_2}x_{2,i}}{n_2}$\n\n**Paired *t*-test:** $\\frac{\\sum_{i=1}^{n}{x_{1,i}-x_{2,i}}}{n}=0$\n\nLet's simulate some data, conduct a paired *t*-test, and convince\nourselves that the paired *t*-test is equivalent to a one-sample test on\npairwise differences.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Example paired t-test in R\n# simulate data\nset.seed(42)\na <- rnorm(100, 5, 2)\n# add pair-wise differences\nb <- a + rnorm(100, 2, 0.2)\n```\n:::\n\n\nInterpretation: The researcher should conclude that the mean difference\nfor each subject was significantly different from 0, at -1.98 with a 95%\nCI of [-2.02, -1.95].\n\nNote that the paired *t*-test gives essentially the same result as\nconducting a one-sample test on the pair-wise differences.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compare to one sample t-test on differences:\n\ndif <- b - a\nt.test(dif)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  dif\nt = 109.63, df = 99, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 1.946622 2.018385\nsample estimates:\nmean of x \n 1.982503 \n```\n\n\n:::\n:::\n\n\n## *t*-test summary {#sec-groups-ttests}\n\nAs we have seen, the *t*-test in all of its variations is a very useful and flexible family of tests that can be applied to many biological problems. One of the reasons that *t*-tests are so widely applicable-and why there are so many *t*-tests--is that the test statistic *t* is so elegant in its construction: it represents the quantity of interest directly in its numerator, and then the denominator scales that quantity according to the level of uncertainty in the data. It is thus a kind of **signal-to-noise ratio** that predated information theory by almost 50 years. \n\nAs a review, the table below summarizes the different *t*-tests and their use cases:\n\n| Type | Use | Section |\n|---|---|---|\n| One-sample *t*-test, one-tailed | Tests whether the population mean of a single set of values is less than or greater than a specified value $\\mu_0$. Appropriate when differences in only one direction are of interest. | @sec-groups-1samp-1t |\n| One-sample *t*-test, two-tailed | Tests whether the population mean is equal to a specified value $\\mu_0$ (null hypothesis) or differs from it (alternative hypothesis). | @sec-groups-1samp-2t |\n| Two-sample *t*-test, two-tailed | Tests whether the population means of two groups ($\\mu_1$ and $\\mu_2$) differ. This can also be thought of as testing whether the difference between the means is equal to 0. Welch's *t*-test, which does not assume equal variances, should generally be used and is the default in R. | @sec-groups-2samp-2t |\n| Two-sample *t*-test, one-tailed | Tests whether the population mean of one group ($\\mu_1$) is less than or greater than the mean of another group ($\\mu_2$). Appropriate when differences in only one direction are of interest. | @sec-groups-2samp-1t |\n| Paired *t*-test | Tests whether the mean difference between paired observations differs from a specified value $D_0$, usually 0. The test may be one- or two-tailed depending on the hypothesis. | @sec-groups-paired-pt |\n\n: Common types of *t*-tests and the hypotheses they evaluate. {#tbl-t-tests}\n\nThe number of \"samples\" in a *t*-test refers to how many sets of\nobservations are being compared. There can be either 1 sample (all\nobservations compared to some value) or 2 samples (2 sets of\nobservations compared to each other).\n\nThe number of \"tails\" refers to how sides (left (negative) and/or right\n(positive)) are of interest in the test statistic distribution. In a\ntwo-tailed test, or two-sided test, an extreme test statistic could fall\nin either the right or the left tail of the distribution. The figure\nbelow shows the range of *t* values which would be declared significant\nfor each kind of test. Notice that for a one-tailed test, the\nsignificance region extends closer to the center, because its area must\nbe equal to the same $\\alpha$ as a two-tailed test.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](ch15_files/figure-pdf/unnamed-chunk-19-1.pdf){fig-align='center'}\n:::\n:::\n\n\nThe *t*-test is usually one of the first methods taught because its use\ncases are simple, and its test statistic is pretty easy to understand.\nConsider the original *t* statistic introduced to the English statistics\nliterature by Gosset and popularized as \"Student's *t*\" by Fisher:\n\n$$\nt=\\frac{\\bar{x_1}-\\bar{x_2}}{\\sqrt{\\frac{s_{x_1}^2+s_{x_2}^2}{2}}\\sqrt{\\frac{2}{n}}}\n$$\n\nThe numerator is the quantity of interest: the difference in sample\nmeans. It should make sense that the larger the difference in sample\nmeans, the greater the probability that the difference will be\nstatistically significant. However, considering only the sample means\n$\\bar{x_1}$ and $\\bar{x_2}$ is not enough. We also need to account for\nvariation within each sample, and for the total sample size. Variance\nshould *decrease* *t*, while sample size should increase it. Both terms\nare put in the denominator so that the difference in means is relative\nto them. Notice that in the denominator, the variances $s_{x_1}^1$ and\n$s_{x_2}^1$ are in a numerator. Thus, increasing them will decrease *t*.\nOn the other hand, the sample size *n* is in a numerator in the\ndenominator (which is tantamount to being in the overall numerator).\nThus, increasing sample size will increase *t*.\n\nBut as elegant as Student's *t* is, it has some drawbacks. It can\nproduce biased estimates and *p*-values when the two groups have unqual\nsample sizes, or unequal variances. For these reasons, a more modern\nversion of the *t* statistic was developed by Welch in the 1940s. This\nis sometimes called the \"Welch's *t*-test\", or less precisely the\n\"Welch-Satterthwaite *t*-test\". Satterthwaite's contribution was not to\nthe *t* statistic, but rather an equation to better calculate the\ndegrees of freedom to use for the test[^09-basic-2].\n\n[^09-basic-2]: This is why *t*-tests in R often report non-integer\n    degrees of freedom.\n\n$$\nt=\\frac{\\bar{x_1}-\\bar{x_2}}{\\sqrt{\\frac{s_1}{\\sqrt{n_1}}+\\frac{s_2}{\\sqrt{n2}}}}\n$$ This newer version has the same numerator, but instead of pooling the\nvariances and sample sizes, keeps them separate. This allows for more\nflexibility when dealing with unequal sample sizes or (mildly)\nheteroscedastic data.\n\n## Tests for 3 or more groups {#sec-groups-more}\n\n### Analysis of variance {#sec-groups-more-anova}\n\nIn this section, we will explore the \"test comparing group means\" sense of analysis of variance (ANOVA) (@sec-review-lin-anova). The linear model version of ANOVA assesses significance using an *F*-test. Much like *t*, *F* is a test statistic that summarizes a quantity of interest in a test that can be compared to the typical strength of a pattern produced by random noise (see @sec-groups-2samp-2t}). Whereas *t* is usually a difference in means scaled by sample size and variance, *F* compares variances. The basic idea of an *F* statistic is:\n\n$$F=\\frac{\\text{explained variance}}{\\text{unexplained variance}}$$\n\nIn the case of a one-way ANOVA, this translates to:\n\n$$F=\\frac{\\text{between-group variability}}{\\text{within-group variability}}$$\n\nThe numerator is essentially the variance in group means:\n\n$$\\sum_{i=1}^Kn_i\\frac{\\left(\\bar{Y}_{i}-\\bar{Y}\\right)^2}{\\left(K-1\\right)}$$\n\nwhere $\\bar{Y}_{i}$ is the sample mean in group $i$, $n_i$ is the number of observations in group $i$, $\\bar{Y}$ is the overall mean of the data, and $K$ is the number of groups.\n\nThe denominator is close to the the sum of within-group variances:\n\n$$\n\\frac{\n\\sum_{i=1}^K\\sum_{j=1}^{n_i}\n\\left(Y_{ij}-\\bar{Y}_i\\right)^2\n}{\nN-K\n}\n$$\n\nwhere $Y_{ij}$ is observation $j$ in group $i$ (out of $K$ groups), and $N$ is the overall sample size.\n\nThe $F$ statistic is a ratio of *variance explained* to *variance not explained*. *F* values follow the *F* distribution, which is defined by degrees of freedom $d_1=K-1$ and $d_2=N-K$ under the null hypothesis. Practically, *F* will be large when there is more explained variance than unexplained variance, which is unlikely if the group means are not different.\n\n**Question:** Do the means differ between groups (with number of groups\n$\\geq2$.\n\n**Null hypothesis:** All group means are equal.\n\n**Alternative hypothesis:** At least one group mean is different from\nthe others.\n\n**Example use case:** Marge needs to test whether cucumber mass is\ngreater in plants grown in potting mix, sandy soil, or clayey soil.\n\nThe nature of the *F* statistic belies the other meaning of ANOVA: the\npartitioning of variation into its different sources. In other words,\nwhat proportion of variation in the *Y* variable does each factor\nexplain? How much variation is due to random chance (i.e., residual\nvariation)? ANOVA in this sense can be applied to many models, including\nall linear models.\n\nThe first step in a typical ANOVA is the **omnibus test**,\nwhich assesses whether *any* of the group means differ\nfrom each other. Then, a **post-hoc test** is performed to check *which* groups differ from each other. \n\nANOVAs are typically described as \"X-way ANOVA\", where X is the number of factors. For example, a test of mean stomach size in herbivorous, carnivorous, and omnivorous mammals would be a \"one-way ANOVA\" because it has one grouping variable, \"diet\". The three groups in the factor diet are the **levels** of the factor.\n\n\n\n#### One-way ANOVA {#sec-groups-more-anova-1way}\n\nWhen there is one explanatory **factor**, or grouping variable, the test is called a **one-way ANOVA** regardless of how many **levels** or groups that factor contains. Here is an example using the built-in example dataset `iris`. There are two common ways to fit an ANOVA in R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# method 1: lm()\nmod1 <- lm(Petal.Length~Species, data=iris)\n\n# method 2: aov()\nmod2 <- aov(Petal.Length~Species, data=iris)\n```\n:::\n\n\nOnce the model is fit, we request the **anova table** so we can see the contributions of each source of variation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# method 1: using lm\nanova(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: Petal.Length\n           Df Sum Sq Mean Sq F value    Pr(>F)    \nSpecies     2 437.10 218.551  1180.2 < 2.2e-16 ***\nResiduals 147  27.22   0.185                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# method 2: using aov\nsummary(mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \nSpecies       2  437.1  218.55    1180 <2e-16 ***\nResiduals   147   27.2    0.19                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nNo matter which method we use, the ANOVA table shows us that the factor `Species` uses 2 degrees of freedom (variously abbreviated as DF, Df, or d.f.) to account for 437.10 of the squared errors; the residuals use 147 d.f. to account for 27.22 of the squared errors. The ratio of the mean squared error per d.f. associated with each source, 218.551 / 0.185 = 1180.2, is the test statistic *F*. This is used to calculate the *P*-value (much like *t*, *F* follows a particular distribution defined by DF, which allows $p(F)$ to be calculated). We can also see that about 94.1% of variation (437.10 / (437.10+27.22)) is associated with species. This is the model’s coefficient of determination, or $R^2$. The $R^2$ tells you the proportion of variation in *Y* explained by the model.\n\n:::{.callout-tip}\n**Rounding errors**\n\nR is somewhat idiosyncratic in choosing how many digits it prints, and this can lead to confusion if values are rounded to too few decimal places. In the ANOVA example above, the MSE for the two sources of variation should divide to the F statistic. However, $218.55/0.19\\neq1180$. If you look at the raw output of `mod1`, however, you that the sums of squares for Species and Residuals are 437.1028 and 27.2226, respectively. With more decimal places, you can then recalculate $\\left(437.1028/2\\right)/\\left(27.2226/147\\right)=1180.161$, the correct $F$ ratio.\n:::\n\nRemember that the all that the omnibus test *p*-value tells you is that\nthe means of at least one pair of species differ. To find out which pair\nor pairs, we need to use a post-hoc test. My favorite is the Tukey’s\nhonest significant difference (HSD) test because it automatically\nadjusts for multiple comparisons.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# method 1:\nTukeyHSD(aov(mod1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = mod1)\n\n$Species\n                      diff     lwr     upr p adj\nversicolor-setosa    2.798 2.59422 3.00178     0\nvirginica-setosa     4.090 3.88622 4.29378     0\nvirginica-versicolor 1.292 1.08822 1.49578     0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# method 2:\nTukeyHSD(mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = Petal.Length ~ Species, data = iris)\n\n$Species\n                      diff     lwr     upr p adj\nversicolor-setosa    2.798 2.59422 3.00178     0\nvirginica-setosa     4.090 3.88622 4.29378     0\nvirginica-versicolor 1.292 1.08822 1.49578     0\n```\n\n\n:::\n:::\n\nThe Tukey output shows us that every group differs from every other, with *p<0.001* (here *p* is rounded to 0, although it can never be 0). The differences in group means are presented with their **95% confidence intervals (CI)**. For example, the difference between the group means of versicolor and setosa is 2.798 cm, with 95% CI = [2.594, 3.002]. Notice that none of these CI include 0: this suggests that a true difference of 0 between any two groups is very unlikely. Even without examining *p*-values, CI provide a useful way to evaluate both the direction and magnitude of differences.\n\nOne of the nice things about the Tukey HSD test is that the *p*-values are automatically adjusted for **multiple comparisons**, a phenomenon where the probability of a false positive goes up as a [researcher performs more tests](https://xkcd.com/882/), using a customized version of the probability distribution for the test statistic. This controls the **family wise error rate**, or total false positive probability for this set of three related tests. \n\nAs with a *t*-test, a boxplot is usually the best way to show the results of an ANOVA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(Petal.Length~Species, data=iris, ylim=c(0, 8))\n```\n\n::: {.cell-output-display}\n![Boxplot showing that petal length is greater in *Iris versicolor* than in *Iris setosa*, and greater still in *Iris virginica*.](ch15_files/figure-pdf/fig-ttestboxplot2-1.pdf){#fig-ttestboxplot2 fig-pos='H' fig-alt='Boxplot showing that petal length is greater in *Iris versicolor* than in *Iris setosa*, and greater still in *Iris virginica*.'}\n:::\n:::\n\n\n#### Two- or more way ANOVA {#sec-groups-more-anova-ways}\n\nWhen there are 2 or more explanatory factors, the test is called a **two-way ANOVA**, or **three-way ANOVA**, and so on. We can add additional factors to an ANOVA with the `+` sign.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make a copy of iris with an extra grouping variable\niris2 <- iris\niris2$Flower <- c(\"purple\", \"pink\")\n\n# fit the two-way ANOVA without interaction\nmod3 <- aov(Petal.Length~Species+Flower, data=iris2)\nsummary(mod3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq  F value Pr(>F)    \nSpecies       2  437.1  218.55 1174.229 <2e-16 ***\nFlower        1    0.0    0.05    0.261   0.61    \nResiduals   146   27.2    0.19                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nAdding the colors that way just repeated them until the column was full: purple, pink, purple, pink, and so on until the new vector had length 150 (the number of rows in `iris`). This essentially distributes the colors randomly with respect to the species and thus the petal lengths, so it should be no surprise that flower color had no effect on petal length ($p=0.61$). A Tukey test confirms the effects of species, and the non-effect of `Flower`. Technically, you don't need to do or report a Tukey test if the main effect is nonsignificant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(mod3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = Petal.Length ~ Species + Flower, data = iris2)\n\n$Species\n                      diff      lwr      upr p adj\nversicolor-setosa    2.798 2.593692 3.002308     0\nvirginica-setosa     4.090 3.885692 4.294308     0\nvirginica-versicolor 1.292 1.087692 1.496308     0\n\n$Flower\n             diff        lwr       upr     p adj\npurple-pink 0.036 -0.1032347 0.1752347 0.6101255\n```\n\n\n:::\n:::\n\n\n#### ANOVA with interaction {#sec-groups-more-anova-inter}\n\nAnother important question is whether there is an **interaction** between two variables. An interaction is a situation where one variable changes the effect of another. To test for an interaction between two variables, use the `*` symbol instead of the `+`. The result `y~x1*x2` is shorthand for `y~x1+x2+x1:x2`. The individual effects of the variables `x1` and `x2` are called their **main effects**. The effect of both together `x1:x2` is the **interaction effect**. If a significant interaction effect is detected, then the main effects should not be interpreted by themselves.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# fit the two-way ANOVA WITH interaction\nmod3 <- aov(Petal.Length~Species*Flower, data=iris2)\nsummary(mod3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Df Sum Sq Mean Sq  F value Pr(>F)    \nSpecies          2  437.1  218.55 1161.375 <2e-16 ***\nFlower           1    0.0    0.05    0.258  0.612    \nSpecies:Flower   2    0.1    0.04    0.201  0.818    \nResiduals      144   27.1    0.19                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe interaction is nonsignificant, so we should instead report the main effects in the model without the interaction (`mod2`). If there is an interaction present, then it becomes impossible to discuss the effects of one variable without discussing the effects of the other. We will explore interactions more in the section on ANCOVA below.\n\n#### Blocking designs {#sec-groups-more-anova-block}\n\n#### Repeated measures ANOVA {#sec-groups-more-anova-rep}\n\n#### Tukey's HSD post hoc test {#sec-groups-more-anova-tukey}\n\n### Kruskal-Wallis test {#sec-groups-more-kw}\n\n**Question:** Are values in one or more groups consistently greater or\nless than values in another group? (number of groups $\\geq3$); essentially extends Wilcoxon test to more groups)\n\n**Null hypothesis:** For randomly selected values $x$ and $y$ from any 2\ngroups, $p\\left(x>y\\right)=p\\left(y>x\\right)$.\n\n**Alternative hypothesis:** For randomly selected values $x$ and $y$\nfrom any 2 groups, $p\\left(x>y\\right)\\neq p\\left(y>x\\right)$\n\n**Example use case:** Bart is studying whether tomato yields tend to be\ngreater in plants treated with no pesticide, pesticide A, or pesticide\nB. He is not interested in predicting the actual tomato yield.\n\nBecause ANOVA is a linear model, the data used in ANOVA must meet the [assumptions of the linear model](@sec-review-lin-assum). If the data do not meet the assumptions, or cannot be transformed to do so, then a nonparametric alternative to ANOVA is needed. The most common alternative is the **Kruskal-Wallis test**. Some texts refer to this as a “nonparametric ANOVA”, but this is not correct because at no point is variance actually partitioned. Like the Wilcoxon test, the Kruskal-Wallis test is based on ranks of the data. A significant Kruskal-Wallis test indicates that values in at least one group are consistently greater than values in at least one other group. As with ANOVA, a post-hoc test is needed to determine which groups differ significantly from each other.\n\n**Example Kruskal-Wallis test in R**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(Petal.Length~Species, data=iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  Petal.Length by Species\nKruskal-Wallis chi-squared = 130.41, df = 2, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe significant result means that petal length is consistently greater\nfor at least species compared to the other. This is analogous to the\nomnibus ANOVA test. If we want to know which groups differ, we need a\npost-hoc test. The most common option is the Dunn's test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dunn.test)\ndunn.test(iris$Petal.Length, iris$Species, method=\"bonferroni\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Kruskal-Wallis rank sum test\n\ndata: x and group\nKruskal-Wallis chi-squared = 130.411, df = 2, p-value = 0\n\n                           Comparison of x by group                            \n                                 (Bonferroni)                                  \nCol Mean-|\nRow Mean |     setosa   versicol\n---------+----------------------\nversicol |  -5.862996\n         |    0.0000*\n         |\nvirginic |  -11.41838  -5.555388\n         |    0.0000*    0.0000*\n\nalpha = 0.05\nReject Ho if p <= alpha/2\n```\n\n\n:::\n:::\n\n\nInterpretation: A posthoc Dunn’s test showed that all three species\ndiffered from each other in terms of the rank order of petal lengths.\n\n## Tests with ordered factors {#sec-groups-ord}\n\nSome factors can represent group membership, but still have an inherent ordering to them. For example, soft drinks come in sizes \"small\", \"medium\", and \"large\". These are categories, but categories in order: small < medium < large. In contrast, the three species in the `iris` dataset have no ordering. \n\nYou may have data with a factor for age, like \"juvenile\", \"subadult\", \"adult\". These categories correspond to ages, but cannot be treated as literal numbers of years or months. It would also be a mistake to treat the comparison of \"juvenile vs. subadult\" the same as the comparison of \"juvenile vs. adult\".\n\nIf you analyze an ordered factor, R will estimate polynomial terms of order up to $k-1$, where $k$ is the number of factor levels. The polynomial function is a way to fit different patterns across the ordered levels. For example, a linear pattern captures a monotonic increase or decrease across the levels. A quadratic pattern can describe a situation where the middle of three levels has greater (or smaller) values than the first and third levels. Let's create a toy dataset to illustrate working with an ordered factor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nages <- c(\"juvenile\", \"subadult\", \"adult\")\ndx <- data.frame(age=rep(ages, each=20))\n# tell R that this is an ordered factor\ndx$age <- factor(dx$age, levels=ages, ordered=TRUE)\n\n# notice the levels statement:\ndx$age\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] juvenile juvenile juvenile juvenile juvenile juvenile juvenile juvenile\n [9] juvenile juvenile juvenile juvenile juvenile juvenile juvenile juvenile\n[17] juvenile juvenile juvenile juvenile subadult subadult subadult subadult\n[25] subadult subadult subadult subadult subadult subadult subadult subadult\n[33] subadult subadult subadult subadult subadult subadult subadult subadult\n[41] adult    adult    adult    adult    adult    adult    adult    adult   \n[49] adult    adult    adult    adult    adult    adult    adult    adult   \n[57] adult    adult    adult    adult   \nLevels: juvenile < subadult < adult\n```\n\n\n:::\n:::\n\n\nHere we use our new factor to plot and analyze french fry consumption across age categories: \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# add y values\ndx$ff <- NA\ndx$ff[which(dx$age==\"juvenile\")] <- rnorm(20, 5, 1)\ndx$ff[which(dx$age==\"subadult\")] <- rnorm(20, 15, 1)\ndx$ff[which(dx$age==\"adult\")] <- rnorm(20, 10, 1)\n\n# inspect the data\nboxplot(ff~age, data=dx, ylab=\"French fry consumption\")\n```\n\n::: {.cell-output-display}\n![Boxplot showing that french fry consumption is greatest in subadults, less in adults, and lowest in juveniles.](ch15_files/figure-pdf/fig-ttestboxplot3-1.pdf){#fig-ttestboxplot3 fig-pos='H' fig-alt='Boxplot showing that french fry consumption is greatest in subadults, less in adults, and lowest in juveniles.'}\n:::\n:::\n\nNow fit the model using the ordered factor `age`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod11 <- aov(ff~age, data=dx)\nsummary(mod11)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)    \nage          2 1008.8   504.4   526.2 <2e-16 ***\nResiduals   57   54.6     1.0                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe omnibus test shows us that `age` is significant. However, because we have an ordered factor, we don't want something like a Tukey test. Group means are not of interest; rather, the pattern in group means across groups is. So, we what we want is to see which patterns across `age` are significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary.lm(mod11)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\naov(formula = ff ~ age, data = dx)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.88500 -0.78190 -0.08528  0.59410  2.17546 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   9.9419     0.1264   78.66   <2e-16 ***\nage.L         3.6275     0.2189   16.57   <2e-16 ***\nage.Q        -6.1060     0.2189  -27.89   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9791 on 57 degrees of freedom\nMultiple R-squared:  0.9486,\tAdjusted R-squared:  0.9468 \nF-statistic: 526.2 on 2 and 57 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe coefficients for `age.L` and `age.Q` are the linear and quadratic trends, respectively. In this case, there is a positive linear trend (`3.5113`), so $Y$ generally increases with age category. There is also a significant negative quadratic trend (`-6.2328`), meaning that the relationship is curved. These trends describe the *shape* of the trend with respect to the age categories, not literally the values of $Y$ given $X$ (as in a polynomial equation), so you need to inspect the boxplot or a plot of means.\n\nThis analysis was simple because there were only 3 levels of `age`. When an ordered factor has many levels, you may observe \"significant\" polynomial trends that are biologically unimportant or difficult to interpret. It is up to you as a biologist to exercise some judgement in deciding how many terms to interpret. For example, a quadratic pattern can be readily interpreted biologically. But what about a quintic? Or an octic?",
    "supporting": [
      "ch15_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}