{
  "hash": "cc1225ae68a3078e92ca957b9dc469ab",
  "result": {
    "engine": "knitr",
    "markdown": "# Tests for continous patterns {#sec-lin}\n\nThis module discusses classic tests for patterns where we relate changes in one continuous variable to another continuous variable. By convention, the **response** or **dependent** variable is plotted on the y-axis, and is taken to be the \"effect\" being studied. The **predictor** or **independent** or **explanatory** variable the one interpreted as the cause. Predictors are plotted on the x-axis. Such a plot or model is said to be of \"y versus x\". \n\nHowever, as we see in the section on correlation, we can also investigate patterns between variables without assuming that one causes the other--only that they reliably change together.\n\n## Correlation {#sec-lin-cor}\n\n**Correlation** is a statistical relationship where changes in one variable are reliably associated with changes in another variable. This relationship need not be causal, hence the famous mantra, “correlation does not equal causation”. As such, correlation is usually a **descriptive technique**, which lets researchers characterize patterns, rather than an **inferential technique**, which lets researchers make estimates about unknown parameters (i.e., infer unobserved quantities). \n\nCorrelations are typically expressed as a **correlation coefficient**, a value that indicates the strength of the correlation by its magnitude and the direction of the correlation by its sign.\n\n- **Positive correlation:** as one variable gets larger, the other variable does too. Correlation coefficient approaches $+1$.\n\n- **Negative correlation:** as one variable gets larger, the other variable gets smaller. Correlation coefficient approaches $-1$.\n\nWhen a correlation coefficient is near 0, this indicates no correlation.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Illustration of possible positive and negative relationships between pairs of variables, with different levels of consistency (*r*).](ch16_files/figure-pdf/fig-correlations-1.pdf){#fig-correlations fig-alt='Illustration of possible positive and negative relationships between pairs of variables, with different levels of consistency (r).'}\n:::\n:::\n\n\n**Correlation coefficients** are often calculated when we want to see if\ntwo values are related, without going as far as to infer a causal\nrelationship. Because science is all about finding explanations (i.e.,\ncauses) for natural phenomena, a correlation analysis is usually not\npresented on its own. However, correlation analysis can be part of a\nlarger workflow:\n\n- Correlations can indicate if some variables in a dataset are *redundant*—that is, any analysis of one would say the same as analyzing the other.\n\n- Correlations can indicate association without inference—e.g., it\n    might be sufficient to know that your residuals are correlated with\n    some other variable, without being able to model the relationship.\n- Correlations can help identify proxy variables—variables that can stand in for one another. E.g., correlation analysis may reveal that an inexpensive, easily obtainable variable is a good stand-in for an expensive, but less obtainable one.\n- Correlations can screen large numbers of variables for possible patterns and inform future investigations. For example, in some analyses I will start by testing many variables for correlations, and only invest time fitting inferential models (e.g., GLMs) for the variables that show some correlation with the response variable.\n\n### Linear correlation {#sec-lin-cor-lin}\n\n**Question:** As values in one set change, do values in another set\nchange at a constant rate?\n\n**Null hypothesis:** N/A (descriptive statistic)\n\n**Alternative hypothesis:** N/A (descriptive statistic)\n\n**Example use case:** Lisa is studying whether the size of a mammal’s\ncecum is related to the proportion of plant material in its diet, and\nsuspects that the relationship is linear.\n\nWhen we suspect that two variables are correlated, and that the shape of that relationship is a straight line, we can use **Pearson's product moment correlation**, also called **Pearson's *r***. This is probably the most commonly used correlation coefficient, and can be calculated in many ways. One way is this:\n\n$$\nr_{xy}=\\frac{\\sum_{i=1}^n\\left(x_i-\\bar{x}\\right)\\left(y_i-\\bar{y}\\right)}{\\sqrt{\\sum_{i=1}^n\\left(x_i-\\bar{x}\\right)^2}\\sqrt{\\sum_{i=1}^n\\left(y_i-\\bar{y}\\right)^2}}\n$$\n\nIn this expression, $r_{xy}$ is the correlation between vectors $x$ and\n$y$; $n$ is the total number of observations; $x_i$ and $y_i$ are the\n*i*-th value of $x$ and $y$, respectively; $\\bar{x}$ and $\\bar{y}$ are the sample\nmeans of $x$ and $y$. This expression shows that *r* gets larger as the slope of the\nrelationship between $x$ and $y$ gets larger, regardless of sign; and\nthat increasing variance decreases *r*.\n\nThe numerator is also called the **covariance** of $x$ and $y$. You might recognize the denominator as the product of the SD of $x$ and $y$. So, the formula for Pearson's *r* can be written very compactly as:\n\n$$\nr_{xy}=\\frac{\\text{cov}\\left(x,y\\right)}{s_xs_y}\n$$\n\nThe base function `cor()` calculates correlation coefficients, including *r*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate linear correlation coefficient\ncor(iris$Petal.Length, iris$Petal.Width)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9628654\n```\n\n\n:::\n:::\n\n\nYou can also request a significance test on the coefficient, although some might consider this unnecessary because correlation is inherently a descriptive technique. If you are using correlation as a hypothesis test, however, you do need a *p*-value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(iris$Petal.Length, iris$Petal.Width)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  iris$Petal.Length and iris$Petal.Width\nt = 43.387, df = 148, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.9490525 0.9729853\nsample estimates:\n      cor \n0.9628654 \n```\n\n\n:::\n:::\n\n\nYou can also get correlations between a set of variables. The result is a\ncorrelation matrix (see @sec-desc-co-lin-pairs).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# correlations between several variables at once:\n# i.e., a correlation matrix\ncor(iris[,1:4])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Sepal.Length Sepal.Width Petal.Length Petal.Width\nSepal.Length    1.0000000  -0.1175698    0.8717538   0.8179411\nSepal.Width    -0.1175698   1.0000000   -0.4284401  -0.3661259\nPetal.Length    0.8717538  -0.4284401    1.0000000   0.9628654\nPetal.Width     0.8179411  -0.3661259    0.9628654   1.0000000\n```\n\n\n:::\n:::\n\n\nThere isn’t a built-in way to check for significant correlations between many pairs of variables at once. This is because `cor.test()` only works with one pair at a time. Fortunately, it’s not hard to do in a `for()` loop:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# data frame with just the variables we need\ndx <- iris[,1:4]\n\n# set up data frame to hold results\n## get the names of the variables\nvar.names <- names(dx)\n## get every unique combination of 2 of those names\nvar.pairs <- combn(var.names, 2)\n## transpose the result (swap rows and columns)\n## so it is oriented like a data frame, and convert\n## from matrix to data frame\ncor.df <- as.data.frame(t(var.pairs))\ncor.df$r <- NA\ncor.df$p <- NA\n\n#### NOTE: you can create the object cor.df more      ##\n####       quickly by combining commands like this:   ##\n##### not run:                                        ## \n##### cor.df <- as.data.frame(t(combn(names(dx),2)))  ##\n\n# find the r and p values in a loop\nfor(i in 1:nrow(cor.df)){\n  # test once per iteration  \n  curr <- cor.test(dx[,cor.df$V1[i]], dx[,cor.df$V2[i]])\n  # pull out values we need from correlation test result\n  # and round to 3 decimal places\n  cor.df$r[i] <- round(curr$estimate, 3)\n  cor.df$p[i] <- round(curr$p.value, 3)\n}#close i loop\n\n# print result\ncor.df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            V1           V2      r     p\n1 Sepal.Length  Sepal.Width -0.118 0.152\n2 Sepal.Length Petal.Length  0.872 0.000\n3 Sepal.Length  Petal.Width  0.818 0.000\n4  Sepal.Width Petal.Length -0.428 0.000\n5  Sepal.Width  Petal.Width -0.366 0.000\n6 Petal.Length  Petal.Width  0.963 0.000\n```\n\n\n:::\n:::\n\n\nIt’s not pretty, but we can see right away that every pair is\nsignificantly correlated except sepal width and sepal length. Remember that the *p*-values printed as `0.000` are not literally 0; report them as \"<0.001\".\n\nAnother way to explore correlations between many pairs of variables is to visualize them in a scatterplot matrix (see @sec-desc-co-lin-pairs).\n\n### Nonlinear correlation {#sec-lin-cor-non}\n\nMany processes and relationships in biology are not linear, and but we still want to study correlations in those processes. So, instead of asking whether or not the assocation is linear, we ask whether it is **monotonic**, meaning that the changes in one variable associated with changes in another tend to have the same sign. For example, as $X$ increases, $Y$ either consistently increases or consistently decreases, but does not go up and down across the domain of $X$.\n\nConsider the figure below. The left panel clearly shows some relationship between $X$ and $Y$, but it is not linear and using a linear correlation coefficient might miss something. The right panel shows the same data points after a [rank transform](@sec-trans-common-rank).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ch16_files/figure-pdf/unnamed-chunk-5-1.pdf)\n:::\n:::\n\n\nOften when two variables share a nonlinear relationship, a rank transform will make that relationship appear more linear. A \"rank-transform\" assigns the smallest value value \"0\", the second smallest value to \"1\", and so on. Rank-transforming these data lets us calculate a nonparametric, nonlinear correlation.\n\n#### Spearman's $\\rho$ {#sec-lin-cor-non-rho}\n \nThe nonparametric equivalent of Pearson’s *r* is Spearman’s $\\rho$ (“rho”). Spearman's $\\rho$ is calculated as the Pearson's *r* linear correlation coefficient of the rank-transformed values.\n\n$$\\rho_{xy}=\\frac{cov\\left(R\\left[x\\right],R\\left[y\\right]\\right)}{s_{R\\left[x\\right]}s_{R\\left[y\\right]}}$$\n\nWhen observations have identical values, their ranks may be tied, which creates some minor issues in the calculation of $\\rho$ and its *p*-value. For this reason, R may throw a warning when calculating a Spearman correlation. You can ignore this warning.\n\nIt can be obtained using code similar to what was done for linear correlation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# just the coefficient\ncor(iris$Petal.Length, iris$Sepal.Width, method=\"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.3096351\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# confirming the connection to Pearson's r\ncor(rank(iris$Petal.Length), rank(iris$Sepal.Width))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.3096351\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# can also get a significance test for rho\ncor.test(iris$Petal.Length, iris$Sepal.Width, method=\"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  iris$Petal.Length and iris$Sepal.Width\nS = 736637, p-value = 0.0001154\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n       rho \n-0.3096351 \n```\n\n\n:::\n:::\n\n\nJust as with linear correlation, you can get a correlation matrix of nonlinear $\\rho$ correlation coefficients, and a scatterplot matrix with `pairs()`. See @sec-desc-co-non-pairs.\n\n#### Kendall's $\\tau$ {#sec-lin-cor-non-tau}\n\nThere is another nonparametric rank-based correlation coefficient,\nKendall’s $\\tau$ (“tau”). Kendall's $\\tau$ is based not upon a correlation coefficient between ranked observations, but instead on the concordance or agreement between the rankings of $x$ and $y$. This means that for any pair of observations $\\left(x_i,y_i\\right)$ and $\\left(x_j,y_j\\right)$, the ranking order of $\\left(x_i,x_j\\right)$ and $\\left(y_i,y_j\\right)$ agree. Put another way, if both $x_i>x_j$ and $y_i>y_j$ *or* $x_i<x_j$ and $y_i<y_j$, then the pair of observations $i$ and $j$ is **concordant**. Any other finding is **discordant**. The original version of Kendall's $\\tau$, now called $\\tau_a$ is thus calculated:\n\n$$\\tau_{xy}=\\frac{\\left(\\text{number of concordant pairs}\\right)-\\left(\\text{number of discordant pairs}\\right)}{\\left(\\text{number of pairs}\\right)}$$\n\nThere is a [more modern version](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient#Tau-b) of $\\tau$, called $\\tau_b$, that can account for ties. This is what the R functions `cor()` and `cor.test()` calculate.\n\nIn practice, Kendall's $\\tau$ and Spearman's $\\rho$ tend to give qualitatively similar results, so you can often choose freely between them. However, there are some situations where $\\tau$ might be preferable. First, the magnitude of $\\tau$ has a much more intuitive meaning than that of $\\rho$. It is related to the degree to which concordant pairs are more common than discordant pairs. E.g., $\\tau=0.6$ indicates roughly that concordant pairs are 60% more common than discordant pairs. When $\\rho=0.6$, on the other hand...well, $\\rho=0.6$.\n\nSecond, $\\tau$ can work better at small sample sizes because its sampling distribution and exact tests are well developed.\n\nFinally, $\\tau$ may be preferred when the data are genuinely ordinal, because of how comparison between ranks is central to the calculation of $\\tau$. This is philosophical rather than computational: $\\rho$ works just fine on ordinal data, too.\n\nThat last thing I'll add is that while $\\rho$ and $\\tau$ address the same question, they go about it in different ways and so they are on different scales. This is why they give qualitatively similar results even when the numbers are different. In fact, $\\rho$ and $\\tau$ have a known relationship under certain conditions:\n\n$$\\tau=\\frac{2}{\\pi}\\arcsin\\left(\\rho\\right)$$\n\nYou can obtain Kendall's $\\tau$ in R with the `method` argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# just the coefficient\ncor(iris$Petal.Length, iris$Sepal.Width, method=\"kendall\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.1859944\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# can also get a significance test for rho\ncor.test(iris$Petal.Length, iris$Sepal.Width, method=\"kendall\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKendall's rank correlation tau\n\ndata:  iris$Petal.Length and iris$Sepal.Width\nz = -3.2197, p-value = 0.001283\nalternative hypothesis: true tau is not equal to 0\nsample estimates:\n       tau \n-0.1859944 \n```\n\n\n:::\n:::\n\n\n## Linear models {#sec-lin-lm}\n\nWe reviewed the definition and properties of linear models in @sec-review-lin. Linear models are an important part of classical, frequentist statistics because of their power and, historically, their ease of computation. Many methods that are taught in introductory statistics classes are just special cases of the linear model: [t-tests](@sec-groups-ttests), [ANOVA](@sec-groups-more-anova), [linear regression](@sec-lin-reg), and so on. As we will see in @sec-glm1, linear models themselves are a special case of an even more powerful, broader framework called the **generalized linear model (GLM)**.\n\n### Lots of analyses are linear models in disguise (or can be)  {#sec-lin-lm-disguise}\n\nOne of the reasons that linear models are so powerful is that many models or curves that people fit to data, even some whose curves are nonlinear, are actually linear models in a statistical sense. A \"linear model\" here does not mean that the graph must be a straight line. It means that the model is built by adding together predictor variables that are multiplied by constants (slopes), and these slopes are used only as multipliers of the predictor variables. For example, both $y=\\beta_0+\\beta_1x$ and $y=\\beta_0+\\beta_1x+\\beta_2x^2+\\beta_3x^3$ are linear models because the coefficients ($beta$ terms) are used only as multipliers of the predictor variables.\n\nOther models that appear nonlinear can *become* linear models through transformation. For example, an exponential model $y=ae^{\\beta_1x}$ is nonlinear, but log-transforming both sides yields the linear expression $\\log\\left(y\\right)=log\\left(a\\right)+\\beta_1x$. The section below illustrates a few of these \"linear models in disguise\" so you can recognize and apply these methods on your own data.\n\n#### Ordinary linear models {#sec-lin-lm-disguise-lm}\n\nThe basic linear regression model is written as\n\n$$y=\\beta_0+\\beta_1x$$\n\nand is the same as the equation for a line that you learned in high school or college algebra: $y=mx+b$. Statisticians just use $\\beta_0$ for the $y$-intercept and $\\beta_1$ for the slope instead of $b$ and $m$.\n\n**Why it's linear:** the parameters $\\beta_0$ and $\\beta_1$ appear only as multipliers or additive constants, and are combined by addition.\n\n#### Polynomials {#sec-lin-lm-disguise-poly}\n\nA polynomial is a function such as $Y=\\beta_0+\\beta_1X+\\beta_2X^2+...+\\beta_kX^k$, where $k$ is the **order** of the polynomial. A polynomial of order 2 is a quadratic equation. A polynomial of order 3 is a cubic, and so on. Polynomials have well-known shapes, such as the parabola of the quadratic function. Any polynomial with order $\\ge2$ will not be a straight line.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Curve shapes produced by polynomial equations of order 1, 2, and 3: linear, quadratic, and cubic, respectively.](ch16_files/figure-pdf/fig-polynomials1-1.pdf){#fig-polynomials1 fig-alt='Curve shapes produced by polynomial equations of order 1, 2, and 3: linear, quadratic, and cubic, respectively.'}\n:::\n:::\n\n\n**Why it's linear:** although the graph may be curved, the parameters $\\beta_0$, $\\beta_1$, $\\beta_2$, and so on appear only as multipliers on predictor variables, are combined by addition, and are not raised to powers, exponentiated, or use inside other functions. So, a polynomial is linear in its predictors. Look what happens in the figure below. On the left, the polynomial $5+2.1x+6.5x^2$ is plotted vs. $x$ and appears nonlinear. On the right, $y$ is plotted against $x^2$ and *is* linear.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Left: a plot of the nonlinear polynomial function $$. Right: The same function plotted against $x^2$ produces a straight line.](ch16_files/figure-pdf/fig-polynomials2-1.pdf){#fig-polynomials2 fig-alt='Curve shapes produced by polynomial equations of order 1, 2, and 3: linear, quadratic, and cubic, respectively.'}\n:::\n:::\n\n\n#### Exponentials {#sec-lin-lm-disguise-exp}\n\nThe exponential function $y=ae^{bx}$ is ubiquitous in biology because it describes compounding growth (like compound interest). This function is not linear, but it can be turned into and analyzed as linear by log-transforming both sides.\n\n![Rick and Morty meme saying this sounds like linear with extra steps.](../images/cont-rickmorty.jpg){#fig-extrasteps fig-cap=\"Well that sounds like linear with extra steps.\"}\n\n**Why it *can be* linear:** While the exponential function appears nonlinear, it can be made linear by log-transforming both sides:\n\n$$log\\left(y\\right)=log\\left(ae^{bx}\\right)$$\n\n$$log\\left(y\\right)=log\\left(a\\right)+log\\left(e^{bx}\\right)$$\n\nand because $log\\left(e^z\\right)=z$:\n\n$$log\\left(y\\right)=log\\left(a\\right)+bx$$\n\nwhich is the form of a straight line with intercept $log\\left(a\\right)$ and slope $b$.\n\n:::{.callout-tip}\n**Logarithm bases**\n\nMathematicians and statisticians almost always work with the **natural logarithm**, which uses Euler's number $e$ ($\\approx2.7182$) as its base. The natural logarithm can be written $log\\left(x\\right)$, $log_e\\left(x\\right)$, or $ln\\left(x\\right)$. Natural log is used because many [equations related to growth or change become easier](https://www.youtube.com/watch?v=m2MIpDrF7Es) when $e$ is the base. In this tutorial, and any math or statistics text, assume natural logarithm.\n\nIn contrast, scientists and engineers often use other bases, like $log_{10}$ or $log_2$, because these are more intuitive for humans. You can use whatever base you like so long as you are clear about what you did. If you are working with R, you will have an easier time working in natural logs because many functions are set up to use it.\n:::\n\n#### Power laws {#sec-lin-lm-disguise-pow}\n\n**Power laws** of the form $Y=aX^b$ are also ubiquitous in biology, as they describe proportional growth. Power laws are similar to exponential functions, but with a key difference: in a power law, $X$ is in the base and is raised to a power, while in an exponential, $X$ is in the exponent of some other base. \n\n**Why it *can be* linear:** Like an exponential, a power law can be linearized by taking the logarithm of both sides.\n\n$$log\\left(Y\\right)=log\\left(aX^b\\right)$$\n\n$$log\\left(Y\\right)=log\\left(a\\right)+b\\times log\\left(X\\right)$$\n\nIn this form, the power law is linear with intercept $log\\left(a\\right)$ and slope $b$.\n\n## Linear regression {#sec-lin-reg}\n\nThe linear regression model describes a pattern where the response variable $Y$ changes as a linear function of the predictor variable $X$. It looks like this:\n\n$$Y=\\beta_0+\\beta_1X+\\varepsilon$$\n\nwhere $\\beta_0$ is the $y$-intercept, $\\beta_1$ is the slope (effect of a unit increase in $X$ on $Y$), and $\\varepsilon$ is residual variation in $Y$ not explained by $X$--the spread of points above or below the line. In a linear model, residual variation follows a normal distribution with mean 0 and some unknown SD $\\sigma_{\\mathrm{res}}$. Each residual $\\varepsilon_i$ follows the same distribution:\n\n$$\\varepsilon_i \\sim \\mathcal{N}\\left(0,\\sigma_{\\mathrm{res}}\\right)$$\n\nwhere $\\mathcal{N}$ signifies the normal distribution.\n\nThe R syntax for linear regression is basically the same as that for ANOVA and the *t*-test we've seen before, or a boxplot for that matter, but this time the right hand side of the formula has a continuous predictor rather than a factor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# fit a linear regression model\nmod5 <- lm(Petal.Length~Petal.Width, data=iris)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# test for significance of terms\nanova(mod5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: Petal.Length\n             Df Sum Sq Mean Sq F value    Pr(>F)    \nPetal.Width   1 430.48  430.48  1882.5 < 2.2e-16 ***\nResiduals   148  33.84    0.23                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# see estimates of parameter coefficients\nsummary(mod5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Petal.Length ~ Petal.Width, data = iris)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.33542 -0.30347 -0.02955  0.25776  1.39453 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1.08356    0.07297   14.85   <2e-16 ***\nPetal.Width  2.22994    0.05140   43.39   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4782 on 148 degrees of freedom\nMultiple R-squared:  0.9271,\tAdjusted R-squared:  0.9266 \nF-statistic:  1882 on 1 and 148 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe `summary()` output tells you a lot about the regression: the coefficients (and their *p*-values), the omnibus ANOVA for the model (the *F* test at the bottom), and the coefficient of determination (Adjusted *R*-squared). Coefficients are identified as the y-intercept $\\beta_0$ (`Intercept`) and by the variable names (e.g., the slope with respect to petal width is `Petal.Width`). Each coefficient is presented as its estimate and SE (e.g., the intercept is `1.08 ± 0.07`). The test statistic *t* for each coefficient is the ratio of the estimate to the SE, and the *p*-value for *t* calculated from a *t*-distribution (much as in a *t*-test). The coefficient of determination $R^2$ is the proportion of variation in $Y$ explained by the model. In this case, about 93% of variation in Petal.Length is explained by Petal.Width.\n\nWhen you present a linear regression, you should present the parameters, their SE, test statistics, and *p*-values in a table. The omnibus $F$ test and $R^2$ can be reported in Results text. Finally, you should present the data as a scatterplot, with the predicted values as a trendline and the 95% CI of that trendline if feasible. Here is how to do that for the model above:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# generate x values over which to draw trendline\nn <- 100\nminx <- min(iris$Petal.Width, na.rm=TRUE)\nmaxx <- max(iris$Petal.Width, na.rm=TRUE)\npx <- seq(minx, maxx, length=n)\n\n# put in a data frame with same variable names as in the model\nprx <- data.frame(Petal.Width=px)\n\n# calculate predicted values and their SE\npred <- predict(mod5, newdata=prx,\n                se.fit=TRUE, interval=\"confidence\")\n\n# best way to get expected value and 95% confidence limits:\n# (use this with linear models)\nprx$mn <- pred$fit[,\"fit\"]\nprx$lo <- pred$fit[,\"lwr\"]\nprx$up <- pred$fit[,\"upr\"]\n\n# when using methods other than linear regression, you can \n# approximate the 95% CI using the predicted values and\n# their SE, by drawing quantiles from the normal distribution\n# defined by predicted value (pred$fit) and SEs (pred$se.fit).\n# When using this with GLMs, you need to keep track of what \n# values are on the link scale, and which are on the \n# data scale.\n### not run:\n### prx$mn <- qnorm(0.5, mean=pred$fit, sd=pred$se.fit)\n### prx$lo <- qnorm(0.025, mean=pred$fit, sd=pred$se.fit)\n### prx$up <- qnorm(0.975, mean=pred$fit, sd=pred$se.fit)\n\n# make the plot\n## include some par options for a more professional figure\n## see ?par for more options\npar(mfrow=c(1,1),              # 1 x 1 figure layout\n    mar=c(5.1, 5.1, 1.1, 1.1), # margin sizes in lines of text\n    lend=1,                    # flat ends on lines\n    las=1,                     # axis text in reading orientation\n    bty=\"n\",                   # no box around figure\n    cex.axis=1.3,              # size of axis text\n    cex.lab=1.3)               # size of axis labels\n\n## make the base plot\nplot(iris$Petal.Width,         # x values\n     iris$Petal.Length,        # y values\n     pch=16,                   # type of points (see ?points)\n     cex=1.2,                  # size of points\n     xlab=\"Petal width (cm)\",  # x axis label\n     ylab=\"Petal length (cm)\", # y axis label\n     xlim=c(0, 2.5),           # limits of x axis\n     ylim=c(0, 8))             # limits of y axis\n\n## add trendline and 95% confidence limits as lines\n## with points(...,type=\"l\")\npoints(prx$Petal.Width, # x values\n       prx$lo,          # y values\n       type=\"l\",        # lines (see ?base::plot)\n       lwd=2,           # line width (1 is default)\n       col=\"red\",       # line color (\"black\" is default)\n       lty=2)           # dashed line (1, solid line, is default)\npoints(prx$Petal.Width, prx$up, type=\"l\", lwd=2, col=\"red\", lty=2)\npoints(prx$Petal.Width, prx$mn, type=\"l\", lwd=2, col=\"red\")\n```\n\n::: {.cell-output-display}\n![Data plotted with the trendline (solid) and its 95% confidence interval (dashed).](ch16_files/figure-pdf/fig-scattertrend-1.pdf){#fig-scattertrend fig-pos='H' fig-alt='Data plotted with the trendline (solid) and its 95% confidence interval (dashed).'}\n:::\n:::\n\n\n\n## Multiple regression {#sec-lin-mult}\n\nLinear regression is easily extended to **multiple linear regression**, where there are >1 continuous predictors. Just as with ANOVA, additional predictor variables are added to the model formula using `+`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod6 <- lm(Petal.Length~Petal.Width + Sepal.Width, data=iris)\nsummary(mod6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Petal.Length ~ Petal.Width + Sepal.Width, data = iris)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.33753 -0.29251 -0.00989  0.21447  1.24707 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  2.25816    0.31352   7.203 2.84e-11 ***\nPetal.Width  2.15561    0.05283  40.804  < 2e-16 ***\nSepal.Width -0.35503    0.09239  -3.843  0.00018 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4574 on 147 degrees of freedom\nMultiple R-squared:  0.9338,\tAdjusted R-squared:  0.9329 \nF-statistic:  1036 on 2 and 147 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nAdding predictors to a multiple regression model will almost always increase the model fit (e.g., proportion of variance explained, $R^2$), but this does not mean you should keep adding predictors. Multiple regression models are vulnerable to **overfitting**, where random noise (i.e., residual variation) is modeled as if it was part of the deterministic part of the model. Multiple regression models are also highly vulnerable to **collinearity**, where the predictors are correlated with each other. When collinear predictors are included in a model, it is impossible for the model to unambiguously partition the sums of squares associated with each predictor.\n\nWhen plotting the results of a multiple linear regression, you should present the effects of all significant predictors. This is done by plotting the expected y value across a range of each predictor, while holding the other predictor (or predictors) constant at their median. This will show the marginal effect of each predictor on its own. Here is a quick example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# simulate some data\n## random number seed\nset.seed(42)\n\n## number of observations\nn <- 100\n\n## x variables\nx1 <- runif(n, 1, 20)\nx2 <- runif(n, 1, 30)\n\n## coefficients\nbeta0 <- 121\nbeta1 <- 6.1\nbeta2 <- -3.1\n\n## expected y values\ney <- beta0 + beta1*x1 + beta2*x2\n\n# add residual variation\nsigma.res <- 7.8\ny <- ey + rnorm(n, 0, sigma.res)\n\n# put in a data frame\ndx <- data.frame(y=y, x1=x1, x2=x2)\n\n# fit the model\nmod7 <- lm(y~x1+x2, data=dx)\n\n# check significance of terms\nanova(mod7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: y\n          Df Sum Sq Mean Sq F value    Pr(>F)    \nx1         1 125985  125985  2486.3 < 2.2e-16 ***\nx2         1  62984   62984  1243.0 < 2.2e-16 ***\nResiduals 97   4915      51                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nAnd check the coefficients:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = y ~ x1 + x2, data = dx)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.2269  -4.4098   0.0963   4.2975  21.6348 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 120.23351    2.11508   56.85   <2e-16 ***\nx1            6.06715    0.12478   48.62   <2e-16 ***\nx2           -3.07237    0.08715  -35.26   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.118 on 97 degrees of freedom\nMultiple R-squared:  0.9746,\tAdjusted R-squared:  0.9741 \nF-statistic:  1865 on 2 and 97 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nNow make a figure showing `y~x1` and `y~x2`. In each panel, hold the other x value at its median to show the marginal effect of the plotted x value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# define sequences of each x value\nplot.n <- 100\n\nminx1 <- min(dx$x1, na.rm=TRUE)\nmaxx1 <- max(dx$x1, na.rm=TRUE)\npx1 <- seq(minx1, maxx1, length=plot.n)\n\nminx2 <- min(dx$x2, na.rm=TRUE)\nmaxx2 <- max(dx$x2, na.rm=TRUE)\npx2 <- seq(minx2, maxx2, length=plot.n)\n\n# medians of x1 and x2\nmedx1 <- median(x1, na.rm=TRUE)\nmedx2 <- median(x2, na.rm=TRUE)\n\n# assemble data frames with all predictors in the model\nprx1 <- data.frame(x1=px1, x2=medx2)\nprx2 <- data.frame(x1=medx1, x2=px2)\n\n# generate predictions\npred1 <- predict(mod7, newdata=prx1,\n                 interval=\"confidence\", se.fit=TRUE)\npred2 <- predict(mod7, newdata=prx2,\n                 interval=\"confidence\", se.fit=TRUE)\n\n# put expected values and 95% CI in their\n# respective data frames\nprx1$mn <- pred1$fit[,\"fit\"]\nprx1$lo <- pred1$fit[,\"lwr\"]\nprx1$up <- pred1$fit[,\"upr\"]\n\nprx2$mn <- pred2$fit[,\"fit\"]\nprx2$lo <- pred2$fit[,\"lwr\"]\nprx2$up <- pred2$fit[,\"upr\"]\n\n# now make the plot\n\n## include some par options for a more professional figure\n## see ?par for more options\npar(mfrow=c(1,2),              # 1 x 2 figure layout\n    mar=c(5.1, 5.1, 1.1, 1.1), # margin sizes in lines of text\n    lend=1,                    # flat ends on lines\n    las=1,                     # axis text in reading orientation\n    bty=\"n\",                   # no box around figure\n    cex.axis=1.3,              # size of axis text\n    cex.lab=1.3,               # size of axis labels\n    xpd=NA)                    # allows points to print in margin\n\n## make the first panel\nplot(dx$x1,          # x values\n     dx$y,           # y values\n     pch=16,         # type of points (see ?points)\n     cex=1.2,        # size of points\n     xlab=\"x1\",      # x axis label\n     ylab=\"y\",      # y axis label\n     xlim=c(0, 20),  # limits of x axis\n     ylim=c(0, 250)) # limits of y axis\n\n## add trendline and 95% confidence limits as lines\n## with points(...,type=\"l\")\npoints(prx1$x1, # x values\n       prx1$lo,          # y values\n       type=\"l\",        # lines (see ?base::plot)\n       lwd=2,           # line width (1 is default)\n       col=\"red\",       # line color (\"black\" is default)\n       lty=2)           # dashed line (1, solid line, is default)\npoints(prx1$x1, prx1$up, type=\"l\", lwd=2, col=\"red\", lty=2)\npoints(prx1$x1, prx1$mn, type=\"l\", lwd=2, col=\"red\")\n\n# make the second panel\n## make the first panel\nplot(dx$x2, dx$y,\n     pch=16, cex=1.2,\n     xlab=\"x2\", ylab=\"y\",\n     xlim=c(0, 30), ylim=c(0, 250))\npoints(prx2$x2, prx2$up, type=\"l\", lwd=2, col=\"red\", lty=2)\npoints(prx2$x2, prx2$up, type=\"l\", lwd=2, col=\"red\", lty=2)\npoints(prx2$x2, prx2$mn, type=\"l\", lwd=2, col=\"red\")\n```\n\n::: {.cell-output-display}\n![](ch16_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n## Analysis of covariance (ANCOVA) {#sec-lin-ancova}\n\nSometimes biologists want to test for effects of one variable while controlling for another. For example, the slope between $Y$ and $X$ might differ between groups. Or, groups might differ only after accounting for some continuous covariate. Here are some specific examples:\n\n- Herbivorous mammals tend to have longer intestines than carnivorous mammals, but only after accounting for the effect of body mass on intestine length. The researcher wants to see how groups differ, but needs to control for a continuous variable (body length) first.\n\n- Humerus length and femur length both increase with body mass in birds, but humerus length increases faster than femur length (i.e., their slopes are different). The researcher wants to test for a difference in a continous relationship, but needs to control for a factor (which bone) first.\n\nThe method for both situations is called **analysis of covariance**, or **ANCOVA**. You can think of ANCOVA as combining linear regression and ANOVA. ANCOVA is especialy useful for studying **interactions**, where one variable changes the effect of another.\n\n![Illustration of ANCOVA without an interaction (different intercepts, same slope) and with an interaction (different intercepts and slopes.)](../images/cont-ancova.jpg){#fig-cont-ancova fig-cap=\"Left: ANCOVA with main effects only, where group membership (a factor variable) affects the intercept of the relationship between Y and X. Right: ANCOVA with interaction effects, where group membership can affect the intercept and the slope (effect of X on Y).\"}\n\nSo that we really understand what an ANCOVA does, let's simulate our own dataset where groups A and B have different slopes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# simulation parameters\nset.seed(42)\nn <- 30\nbeta0_a <- 2\nbeta0_b <- 6\nbeta1_a <- 1.4\nbeta1_b <- 2.5\nsigma_res <- 2\n\n# groups A and B start in separate data frames\ndata_a <- data.frame(group=\"A\", col=\"red\", pch=15, x=runif(n, 5, 20))\ndata_b <- data.frame(group=\"B\", col=\"blue\", pch=16, x=runif(n, 5, 20))\n\n# add expected values\ndata_a$ey <- beta0_a + beta1_a * data_a$x\ndata_b$ey <- beta0_b + beta1_b * data_b$x\n\n# combine to single data frame\ndata_all <- rbind(data_a, data_b)\n\n# add residuals\ndata_all$y <- data_all$ey + rnorm(n*2, mean=0, sd=sigma_res)\n\n# and make a plot to inspect our data\nplot(data_all$x, data_all$y, col=data_all$col, pch=data_all$pch,\n     xlim=c(0, 20), ylim=c(0, 60))\n```\n\n::: {.cell-output-display}\n![](ch16_files/figure-pdf/unnamed-chunk-18-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nNow we can fit the ANCOVA and see the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# fit the model. Notice the * to specify an interaction\nmod7 <- lm(y~x*group, data=data_all)\n\n# test significance of terms\nanova(mod7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: y\n          Df Sum Sq Mean Sq  F value    Pr(>F)    \nx          1 3507.2  3507.2 1012.289 < 2.2e-16 ***\ngroup      1 5664.0  5664.0 1634.827 < 2.2e-16 ***\nx:group    1  311.0   311.0   89.778 3.108e-13 ***\nResiduals 56  194.0     3.5                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nNow check the model parameters\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = y ~ x * group, data = data_all)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.5122 -0.9491  0.4801  1.1691  3.8166 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.44990    1.17053   0.384 0.702170    \nx            1.49194    0.07883  18.925  < 2e-16 ***\ngroupB       5.62958    1.55677   3.616 0.000642 ***\nx:groupB     1.03148    0.10886   9.475 3.11e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.861 on 56 degrees of freedom\nMultiple R-squared:  0.9799,\tAdjusted R-squared:  0.9789 \nF-statistic: 912.3 on 3 and 56 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nR treats group A as the control or **baseline** because it is alphabetically first. Any effect involving group B is relative to the effect in group A. Here:\n\n- The intercept in group A is `(Intercept)`, 0.4499.\n- The slope in group A is `x`, 1.4919.\n- The intercept in group B is the group A intercept plus the effect of being in group B: $0.4499 + 5.6295=6.0794$.\n- The slope in group B is the slope in group A plus the effect of being in group B on the slope: $1.4919 + 1.0314=2.5233$`\n\nMaking a plot with trendlines for an ANCOVA follows much the same procedure as we used to make the plot for linear regression, but, you have to take care to include each group. Notice that when plotting a line for each group, we make sure to define the line only for the range of x values present in that group in the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# get x sequence within the x domain of each group\npxa <- seq(min(data_all$x[data_all$group==\"A\"]),\n           max(data_all$x[data_all$group==\"A\"]),\n           length=100)\npxb <- seq(min(data_all$x[data_all$group==\"B\"]),\n           max(data_all$x[data_all$group==\"B\"]),\n           length=100)\n# put in data frames\nprxa <- data.frame(group=\"A\", x=pxa)\nprxb <- data.frame(group=\"B\", x=pxb)\n\n# calculate predictions\npreda <- predict(mod7, newdata=prxa, se.fit=TRUE)\npredb <- predict(mod7, newdata=prxb, se.fit=TRUE)\n\n# add to data frames\nprxa$mn <- qnorm(0.5, preda$fit, preda$se.fit)\nprxa$lo <- qnorm(0.025, preda$fit, preda$se.fit)\nprxa$up <- qnorm(0.975, preda$fit, preda$se.fit)\n\nprxb$mn <- qnorm(0.5, predb$fit, predb$se.fit)\nprxb$lo <- qnorm(0.025, predb$fit, predb$se.fit)\nprxb$up <- qnorm(0.975, predb$fit, predb$se.fit)\n\n# make the plot\npar(mar=c(5.1, 5.1, 1.1, 1.1), bty=\"n\", las=1, lend=1,\n    cex.axis=1.3, cex.lab=1.3)\nplot(data_all$x, data_all$y, col=data_all$col, pch=data_all$pch,\n     xlim=c(0, 20), ylim=c(0, 60))\npoints(prxa$x, prxa$mn, type=\"l\", lwd=2, col=\"red\")\npoints(prxa$x, prxa$lo, type=\"l\", lwd=2, col=\"red\", lty=2)\npoints(prxa$x, prxa$up, type=\"l\", lwd=2, col=\"red\", lty=2)\npoints(prxb$x, prxb$mn, type=\"l\", lwd=2, col=\"blue\")\npoints(prxb$x, prxb$lo, type=\"l\", lwd=2, col=\"blue\", lty=2)\npoints(prxb$x, prxb$up, type=\"l\", lwd=2, col=\"blue\", lty=2)\nlegend(\"topleft\", legend=c(\"Group A\", \"Group B\"),\n       pch=c(15, 16), col=c(\"red\", \"blue\"), cex=1.4,\n       bty=\"n\")\n```\n\n::: {.cell-output-display}\n![Plot of Y vs. X with groups A and B in the data, where the groups have different slopes. This illustrations ANCOVA with an interaction between X and group.](ch16_files/figure-pdf/fig-ancovatrend-1.pdf){#fig-ancovatrend fig-pos='H' fig-alt='Plot of Y vs. X with groups A and B in the data, where the groups have different slopes. This illustrations ANCOVA with an interaction between X and group.'}\n:::\n:::\n\n\n### Main effects and interaction effects  {#sec-lin-ancova-inter}\n\n",
    "supporting": [
      "ch16_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}